### ISSUE TITLE
ENH: Scale option in compcor

### ISSUE THREAD

**Issue by muschellij2** [stnava/ANTsR#100]
I think `scale` could be an option in `compcor`.  If the high variance voxels are not scaled, the first PC that comes out will represent the mean, which may not be wanted from the user.

**Comment by stnava** [comment]
Good idea .... Will add later unless you want to make a pull request.

On Friday, April 8, 2016, John Muschelli <notifications@github.com> wrote:

> I think scale could be an option in compcor. If the high variance voxels
> are not scaled, the first PC that comes out will represent the mean, which
> may not be wanted from the user.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/stnava/ANTsR/issues/100>
>


-- 

brian

**Comment by stnava** [comment]
here is how i interpreted your suggestion: https://github.com/stnava/ANTsR/commit/70e33a85b337626f54f9982f913d1e65172b241d

let me know if you agree that this is clear enough.

**Comment by muschellij2** [comment]
Agreed
