### ISSUE TITLE
negative values for iMath( ..., 'D' )

### ISSUE THREAD

**Issue by ntustison** [stnava/ANTsR#102]
When I calculate the distance image using iMath, e.g.

```
fiMask <- getMask( antsImageRead( getANTsRData( 'r16') ) )
fiDistance <- iMath( fiMask, 'D')
antsImageWrite( fiDistance, 'r16Distance.nii.gz' )
```

the foreground labels are all '0' as opposed to what the ITK implementation of Maurer produces---decreasing negative values with interior distance from the boundary.  Is this expected behavior?

**Comment by stnava** [comment]
There may be a separate Maurer implementation ... This may be danielsson.

On Saturday, June 18, 2016, Nick Tustison <notifications@github.com> wrote:

> When I calculate the distance image using iMath, e.g.
>
> fiMask <- getMask( antsImageRead( getANTsRData( 'r16') ) )
> fiDistance <- iMath( fiMask, 'D')
> antsImageWrite( fiDistance, 'r16Distance.nii.gz' )
>
> the foreground labels are all '0' as opposed to what the ITK
> implementation of Maurer produces---decreasing negative values with
> interior distance from the boundary. Is this expected behavior?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/stnava/ANTsR/issues/102>, or mute the thread
> <https://github.com/notifications/unsubscribe/AATyfjExP77siX_0RRxDz3fWUokTdLnMks5qNDAFgaJpZM4I4_2->
> .
>


-- 

brian

**Comment by ntustison** [comment]
Ahhh, I see.  Thanks.

**Comment by stnava** [comment]
`iMath( 0 , "GetOperations" )` lists the operations

**Comment by ntustison** [comment]
Ah, there it is.  Mochas gracias.

**Comment by dorianps** [comment]
I don't know if this is helpful, but I have used iMath('D') to compute Hausdorf distances and they match perfectly the values I get from another C++ implementation. So I guess the implementation is accurate.

**Comment by jeffduda** [comment]
'D' uses the Danielsson filter

**Comment by ntustison** [comment]
Thanks.

**Comment by jeffduda** [comment]
Can add a function for Maurer distance if you want. We take requests

**Comment by ntustison** [comment]
No, it's there.  It was my mistake.

```
> iMath( 0 , "GetOperations" )
 [1] PadImage              D                     MaurerDistance       
 [4] PeronaMalik           Grad                  Laplacian            
 [7] Canny                 HistogramEqualization MD                   
[10] ME                    MO                    MC                   
[13] GD                    GE                    GO                   
[16] GC                    FillHoles             GetLargestComponent  
[19] LabelStats            Normalize             TruncateIntensity    
[22] Sharpen              
22 Levels: Canny D FillHoles GC GD GE GetLargestComponent GO ... TruncateIntensity
```
