### ISSUE TITLE
`antsRegistration` step size differences from ANTs

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#105]
I have noticed that `antsRegistration` with SyNCC in R has much bigger step sizes than `antsRegistrationSyN.sh` for linear transformation (i.e., Rigid[1], Affine[1] vs Rigid[0.1], Affine[0.1]). Does this make a huge difference, is this set on purpose so different in R?

**Comment by dorianps** [comment]
A quick report on the comparison ANTs vs ANTsR:
 `antsRegistration` with SyNCC has better registration than the shell `antsRegistrationSyN.sh`. I have noticed this before as well. The example results are here:

[templateBrain.nii.gz](https://github.com/stnava/ANTsR/files/369217/templateBrain.nii.gz)
[ANTsR_withSyNCC.nii.gz](https://github.com/stnava/ANTsR/files/369218/OnPenn_N4brain_PeronaMalik.nii.gz)
[ANTs_fromShell
[RegistrationMask_without_Lesion.nii.gz](https://github.com/stnava/ANTsR/files/369223/masknolesion.nii.gz)
.nii.gz](https://github.com/stnava/ANTsR/files/369222/ShellSubOntemp.nii.gz)

Commands that lead to above results:
# Shell
  antsRegistration --dimensionality 3 --float 0 \
        --output [$thisfolder/pennTemplate_to_${sub}_,$thisfolder/pennTemplate_to_${sub}_Warped.nii.gz] --interpolation Linear --winsorize-image-intensities [0.005,0.995] --use-histogram-matching 0 --initial-moving-transform [$t1brain,$template,1] --transform Rigid[0.1] --metric MI[$t1brain,$template,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform Affine[0.1] --metric MI[$t1brain,$template,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform SyN[0.1,3,0] --metric CC[$t1brain,$template,1,4] --convergence [100x70x50x20,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox \
            -x $brainlesionmask

#ANTsR  
regist=antsRegistration(fixed = n4denoisedbrain, moving = templatebrain, typeofTransform = 'SyNCC', mask = masknolesion)

**Comment by stnava** [comment]
@ntustison - see above .... not sure if you have any guesses as to the meaning of this observation from @dorianps .... it may be relevant in that i recently changed some of the default behavior in `antsRegistration.R` ... may need to change `antsRegistration.R` again for backward compatibility.

**Comment by stnava** [comment]
i addressed SyNCC backward compatibility with this commit 6b4986efba37c05d7e26e2551e1d4025f7654f1a

**Comment by ntustison** [comment]
I don't know.  As you know, it's hard to make an assessment for n=1 cases.  It doesn't look like the difference is occurring during the linear stages.  Would be nice to actually see the ``antsRegistration`` call for the SyNCC option for this particular case.
