### ISSUE TITLE
SCCAN tutorial has incomplete code

### ISSUE THREAD

**Issue by cedricx** [stnava/ANTsR#108]
SCCAN tutorial online: http://stnava.github.io/sccanTutorial/  has incomplete code, which makes it difficult to follow along. 
The markdown file included in the SCCAN github site contains the complete code: https://github.com/stnava/sccanTutorial/blob/gh-pages/sccanTutorial.Rmd
Maybe generate a new markdown html and publish it on the tutorial site?

**Comment by stnava** [comment]
happy to accept a pull request if thats possible


brian

**Comment by cookpa** [comment]
What is missing? Is it just the first block above the introduction of the RMD?

**Comment by cedricx** [comment]
for example:

In the Sparse Regression section, the online tutorial has the following
code, which doesn't produce the figures shown.

agemat<-matrix( ptraincog$age,
ncol=1)paramsearch<-c(1:10)/(-100.0)paramsearchcorrs<-rep(0,length(paramsearch))paramsearchpreds<-rep(0,length(paramsearch))ct<-1for
( sp in paramsearch ) {
  ageresult<-sparseDecom2( inmatrix=list(ptrainimg,agemat), its=8, mycoption=1,
    sparseness=c(sp,0.9), inmask=c(mask,NA),nvecs=2, cthresh=c(50,0))
  # convert output images to matrix so we can validate in test data
  ccamat<-imageListToMatrix( ageresult$eig1, mask )
  agepred<-ptrainimg %*% t(ccamat)
  paramsearchcorrs[ct]<-cor( agepred[,1],  ptraincog$age )
  agepred<-ptestimg %*% t(ccamat)
  paramsearchpreds[ct]<-cor( agepred[,1],  ptestcog$age )
  ct<-ct+1
  }mydf<-data.frame( sparseness=paramsearch, trainCorrs=paramsearchcorrs,
  testCorrs=paramsearchpreds )mdl1<-lm( trainCorrs ~
stats::poly(sparseness,4), data=mydf )mdl2<-lm( testCorrs ~
stats::poly(sparseness,4) , data=mydf )visreg(mdl1)

The markdown tutorial instead has the following code, which does produce
the figures shown.

agemat<-matrix( ptraincog$age,
ncol=1)paramsearch<-c(1:10)/(100.0)paramsearchcorrs<-rep(0,length(paramsearch))paramsearchpreds<-rep(0,length(paramsearch))ct<-1nvox
= sum( mask >= 0.5 )imat = abs( t(replicate(2,
rnorm(ncol(ptrainimg)))) )for ( sp in paramsearch ) {
  imats=imat
  imats[1, order(imat[1,])[1:round(nvox*(1-abs(sp)))] ]=0
  imats[2, order(imat[2,])[1:round(nvox*(1-abs(sp)))] ]=0
  initdf<-initializeEigenanatomy( imats, mask=mask )
  inmats = list( scale(ptrainimg), scale(agemat))
  ageresult<-sparseDecom2( inmatrix=inmats, its=its,
    sparseness=c(sp, 0.9), inmask=c(mask,NA),nvecs=2, mycoption=copt,
    cthresh=c(1000,0), ell1=10,
    smooth=smth, verbose=verb ) # initializationList = initdf$initlist,
  sccanimg1=matrixToImages( t(ageresult$eig1), mask )[[1]]
  # validate in test data
  agepred<-ptrainimg %*% (ageresult$eig1)
  paramsearchcorrs[ct]<-abs( cor( agepred[,1],  ptraincog$age ) )
  agepred<-ptestimg %*% ageresult$eig1
  paramsearchpreds[ct]<-abs( cor( agepred[,1],  ptestcog$age ) )
  print(paste(sp,paramsearchcorrs[ct],paramsearchpreds[ct]))
  ct<-ct+1
  }mydf<-data.frame( sparseness=paramsearch, trainCorrs=paramsearchcorrs,
  testCorrs=paramsearchpreds )mdl1<-lm( trainCorrs ~
sparseness+I(sparseness^2), data=mydf )mdl2<-lm( testCorrs ~
sparseness+I(sparseness^2), data=mydf )
visreg(mdl1)
visreg(mdl2)



Cedric

**Comment by ntustison** [comment]
I was just about to post a question and saw this issue.  If you're interested, I completely rewrote Brian's tutorial for a workshop I'm giving next month and posted it [here](https://github.com/ntustison/BrianSccanTutorial).  Here's the final pdf [output](https://github.com/ntustison/BrianSccanTutorial/blob/master/tutorial.pdf?raw=true).  There's some aesthetic deviations I made from the original and I have a couple comments to add but it's mostly complete.  If you have the packages specified, you should be able to produce all the figures.
