### ISSUE TITLE
DOI for ANTsR

### ISSUE THREAD

**Issue by armaneshaghi** [stnava/ANTsR#11]
We could get a DOI for ANTsR and make the whole software [citable](https://zenodo.org). Objections?

Step by step guide:

https://guides.github.com/activities/citable-code/

**Comment by bkandel** [comment]
Not sure if we should do this or go for a proper publication in JSS or
similar.  Brian--do you have thoughts?

**Comment by stnava** [comment]
i would prefer to try http://www.jstatsoft.org/


brian

**Comment by armaneshaghi** [comment]
That would be excellent...

**Comment by jefferis** [comment]
Just to add that jss can take a while if you want something in the interim I have used zenodo.org.

**Comment by stnava** [comment]
interesting comments here: http://robjhyndman.com/hyndsight/jss-rpackages/

**Comment by stnava** [comment]
another fantastic reference:   http://www.sciencedirect.com/science/article/pii/S0167947308001606

**Comment by bkandel** [comment]
My inclination is that it's worth it to do it "properly" and get it up to
JSS standards, and then have one unambiguous place to cite, even if it
takes a few months more to get out.  We've invested enough time in this
package that it's worth it to do the "advertising"/taking credit properly.

**Comment by stnava** [comment]
agreed ... and it's good to know, now, what the "beyond cran" standards of
jss are ....


brian

**Comment by armaneshaghi** [comment]
nice blog post for JSS standards, definitely worth the time, I'm sure we
will all be learning lots of things in the process (as I have already
learned a lot). Am happy to work on this even if it takes a year or so
