### ISSUE TITLE
WIP: RIPMMARC

### ISSUE THREAD

**Issue by stnava** [stnava/ANTsR#113]
referencing https://www.google.com/url?hl=en&q=https://github.com/stnava/ANTsR/commit/63db009342924b41f7b870f64133f2a753e330ce%23commitcomment-19179207&source=gmail&ust=1475072330547000&usg=AFQjCNHQSdPXonCBtJZnEduhzporE797hw

and https://www.ncbi.nlm.nih.gov/pubmed/25449745

i have a first compiling/callable version but it does not produce any meaningful output yet.

TODO ( in order of priority )
- PERF: define what output should be  ( @bkandel  your feedback is appreciated here, design-wise )
- DOC: meaningful tests/examples/vignettes
- ENH: return patch images or provide approach to convert patch vectors to images so they can be displayed
- STYLE: replace stand-alone functions with member functions within RIPMMARC filter ( IsInside, ConvertVectorToSpatialImage, GenerateMaskImageFromPatch )

@ntustison if you have a chance to take a look at the RIPMMARC filter in ANTsR/src, that would be great ( though after we get some of the above done ) ... probably better for this filter to live in ants, ultimately.

**Comment by stnava** [comment]
@bkandel you have a comment reading:

```
  // the SECOND eigenvector is canonical--1st is constant
```

to which i ask:

```
  // FIXME - is this always the case?  what if you mean center?
```

**Comment by stnava** [comment]
was able to make more progress today than expected:

updated TODO ( in order of priority )

* DOC: meaningful tests/examples/vignettes - some progress here but nothing really helpful
* ENH: return patch images or provide approach to convert patch vectors to images so they can be displayed ... see below, not sure this will work in general or if it is even working now
* STYLE: replace stand-alone functions with member functions within RIPMMARC filter ( IsInside, GenerateMaskImageFromPatch )
 
examples:

```
library( ANTsR )
img <- antsImageRead( getANTsRData( "r16" ) )
msk <- thresholdImage( img, quantile( img[ img > 0 ] )[1], max( img ) )
ripped <- ripmmarc( img, msk, patchRadius=5, patchSamples=25000,
  meanCenter = FALSE, patchVarEx=20, verbose=TRUE )
ripped3 <- ripmmarc( img, msk, patchRadius=5, patchSamples=250,
    canonicalFrame = ripped$canonicalFrame,
    evecBasis = ripped$basisMat,
    meanCenter = FALSE, patchVarEx=20, verbose=TRUE )
img2 <- antsImageRead( getANTsRData( "r64" ) )
msk2 <- thresholdImage( img2, quantile( img2[ img2 > 0 ] )[1], max( img2 ) )
ripped4 <- ripmmarc( img2, msk2, patchRadius=5, patchSamples=250,
    canonicalFrame = ripped$canonicalFrame,
    evecBasis = ripped$basisMat,
    meanCenter = FALSE, patchVarEx=20, verbose=TRUE )
################################################################################
mm = thresholdImage( abs( ripped$canonicalFrame ), 1.e-20, Inf )
mm2 = antsImageClone( mm )
for (k in 1:nrow( ripped$basisMat ) )
  {
  mm2[mm==1] =  ripped$basisMat[k,]
  print( k )
  plot( mm2, doCropping=F )
  Sys.sleep( 3 )
  img2[msk2==1] =  ripped4$evecCoeffs[,k]
  print( k )
  plot( img2, doCropping=F )
  Sys.sleep( 3 )
  img[msk==1] =  ripped3$evecCoeffs[,k]
  print( k )
  plot( img, doCropping=F )
  img[msk==1] =  ripped$evecCoeffs[,k]
  print( k )
  plot( img, doCropping=F )
  }
```

**Comment by stnava** [comment]
@bkandel - i think the main thing i would like to have some verification/feedback/resolution for is conversion from image domain to patch domain and back.  e.g. for looking at the patch basis function as well as looking at the eigenCoefficients and/or regressing coefficients (in R) on images.

**Comment by stnava** [comment]
updated TODO as of commit 2fd083844a03b5134c4c2051e6d7fb755a0b4604

* DOC: meaningful tests/examples/vignettes - some progress here but nothing really helpful - would be good to have an example that mimics the paper pretty closely ie regression of one modality on another
* STYLE: replace stand-alone functions with member functions within RIPMMARC filter ( IsInside )

**Comment by stnava** [comment]
@ntustison if you get a chance, can you look over https://github.com/stnava/ANTsR/blob/master/src/itkRIPMMARCImageFilter.h and https://github.com/stnava/ANTsR/blob/master/src/itkRIPMMARCImageFilter.hxx

with the idea of moving these to ants

*low priority* but *would be nice*

**Comment by ntustison** [comment]
Looks interesting.   Would love to.

**Comment by stnava** [comment]
thanks - it's been a while since i've put together a filter so there are probably some style/performance issues.   also, this can likely be (pretty easily and profitably) multi-threaded but i want to get better testing set up before going that route.  finally, i think there may be some computational / memory access bug but i havent a way to reproduce it yet so that will have to wait ... just a heads up in case you see anything suspicious.

**Comment by stnava** [comment]
there are also some logic/usage issues in terms of full sampling and subset sampling ....  might be worth thinking about a more complete redesign ... i've made only small modifications from ben's original version.

**Comment by stnava** [comment]
```
#### 3D ####
library( ANTsR )
ch2 = antsImageRead( getANTsRData( 'ch2' ) )
msk2 <- thresholdImage( ch2, quantile( ch2[ ch2 > 0 ] )[1], max( ch2 ) ) %>%
  iMath( "ME", 25 )
ripped <- ripmmarc( ch2, msk2, patchRadius=8, patchSamples=10000,
  meanCenter = FALSE, patchVarEx=20, verbose=TRUE )
ch2evfull = cropImage( ch2, msk2 )
msk2sub = cropImage( msk2, msk2 )
for ( k in 1:10 )
  {
  print( k )
  ch2ev = ripmmarcBasisImage( ripped$canonicalFrame, ripped$basisMat[k,] )
  plot( ch2ev, doCropping=F )
  Sys.sleep( 5 )
  ch2evfull[ msk2sub == 1 ] = ripped$evecCoeffs[,k]
  plot( ch2evfull , doCropping=F )
  Sys.sleep( 5 )
  }
```

**Comment by bkandel** [comment]
Thanks! This looks great. I'll give it a more thorough lookover in the next
couple of days.

2016-09-28 13:51 GMT-04:00 stnava <notifications@github.com>:

**Comment by stnava** [comment]
nice ... i am working on one more example for you to look over - hopefully
will be committed to docs today.


brian

**Comment by stnava** [comment]
updated TODO as of commit f98c447245467d21c763f00b2ed91ce6fc685fa1

* DOC: meaningful tests/examples/vignettes - have one simple example that roughly mimics the paper but not sure this is ideal.

* PERF: need more testing, esp for (esp 3D) rotation invariant version.

* DOC: need to illustrate different possible use cases for the dictionary, extension to other decompositions, etc.
