### ISSUE TITLE
installing ANTsR from source in CentOS

### ISSUE THREAD

**Issue by meccaLeccaHi** [stnava/ANTsR#115]
Hi guys, I am trying to install ANTsR in CentOS, using R CMD commands. ITKR installed without any issues. But I get the several errors during installation of ANTsR. The actual string of errors is quite long, but they mainly seem to involve Atropos.cpp. See example below. Any suggestions? Thanks in advance

In file included from /Users/apjons/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp.h(85),
                 from Atropos.cpp(4):
/Users/apjons/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp/algorithm.h(153): warning #858: type qualifier on return type is meaningless
          static inline RCPP_CONSTEXPR double ZERO() { return 0.0; }
                        ^

In file included from /Users/apjons/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp.h(85),
                 from Atropos.cpp(4):
/Users/apjons/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp/algorithm.h(154): warning #858: type qualifier on return type is meaningless
          static inline RCPP_CONSTEXPR double ONE() { return 1.0; }
                        ^

In file included from /Users/apjons/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp.h(85),
                 from Atropos.cpp(4):
/Users/apjons/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp/algorithm.h(162): warning #858: type qualifier on return type is meaningless
          static inline RCPP_CONSTEXPR int ZERO() { return 0; }
                        ^

In file included from /Users/apjons/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp.h(85),
                 from Atropos.cpp(4):
/Users/apjons/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp/algorithm.h(163): warning #858: type qualifier on return type is meaningless
          static inline RCPP_CONSTEXPR int ONE() { return 1; }

**Comment by stnava** [comment]
not sure about that one ... we use antsr on centos regularly.   e.g. installed recently on CentOS release 6.8 (Final) ... use ` cat /etc/system-release` to find your system version.

**Comment by cookpa** [comment]
I built the master HEAD successfully yesterday with:

R 3.2.3
GCC 4.4.7
CentOS 6.6

I used the devtools method:

```
library( devtools )
install_github("stnava/ITKR")
install_github("stnava/ANTsR")
```

**Comment by meccaLeccaHi** [comment]
Right- that was it. I had failed to load GCC as an environment module. Thanks guys.
