### ISSUE TITLE
ANTsR on Windows 10 (and FSL, Rstudio, Freesurfer etc)

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#118]
Good news!

Windows 10 has enabled a full Ubuntu subsystem that enables `bash` and allows any kind of Linux packages to be installed. You can now have ANTsR, ANTs, FSL, Freesurfer directly on Windows 10. Things work only if your Windows 10 is updated with the anniversary update (Aug 2016)

# Here are the instructions to get ANTsR running
### Enable the Linux subsystem on windows
Follow the instructions here: https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

### Install R-base and git
```
sudo apt-get install r-base-core # for me, installs R 3.0.2
sudo apt-get install git
```

### Install ITKR and ANTsR  
Don't forget to install ANTsR dependencies
```
git clone https://github.com/stnava/ITKR.git
git clone https://github.com/stnava/ANTsR.git
sudo apt-get install cmake
sudo R CMD INSTALL ITKR
# install ANTsR dependencies
# start R and paste the install.packages command from:
# https://github.com/stnava/ANTsR/wiki/ANTsR-Dependencies-for-(close-to)-full-functionality
sudo R CMD INSTALL ANTsR
```
  
Voila! you now have ANTsR on Windows.  
  
Now, Microsoft stys the Linux subsystem don't support gui applications in the Linux subsystem. This would mean that you can't plot in R. But the [workaround is ready]  (http://www.pcworld.com/article/3055403/windows/windows-10s-bash-shell-can-run-graphical-linux-applications-with-this-trick.html). **[Install Xming](https://sourceforge.net/projects/xming/)** (an X-client) on Windows and open it. You will see the icon on system tray. Then, run the following command in the Windows bash:
```
export DISPLAY=:0
```

### Now you can install Rstudio:
```
sudo apt-get install gdebi-core
# get rstudio 64bit for Ubuntu https://www.rstudio.com/products/rstudio/download/
sudo apt-get install libxslt1-dev # library needed for rstudio
sudo gdebi rstudio-0.99.903-amd64.deb # rstudio install
```

### Or Freesurfer ([follow these instructions](http://stackoverflow.com/questions/32530340/freesurfer-installed-on-ubuntu))
(Note, Freeview is not working yet for me. May need to try other Freesurfer version. Recon-all seems to be working but have't tried it)

### I have tried the GUI for FSL, Rstudio, R plots, all working fine.

It might be worth putting similar instructions from ANTsR installation page.

**Comment by dorianps** [comment]
Never mind, posted the necessary information in the [wiki](https://github.com/stnava/ANTsR/wiki/Installing-ANTsR-in-Windows-10-(along-with-FSL,-Rstudio,-Freesurfer,-etc).).

**Comment by stnava** [comment]
thanks - interesting - will add link to installation instrux

**Comment by dorianps** [comment]
I posted a new Wiki page on WSL2 and updated the frontpage README:
https://github.com/ANTsX/ANTsR/wiki/Installing-ANTsR-on-Windows-10-(using-WSL2)

What I did not know was the dramatic improvement in speed when switching from standard BLAS to OpenBLAS. I included the instructions in the Wiki. Has anybody done any serious testing of OpenBLAS on a real ANTsR process (curious if SCCAN is betteR).
