### ISSUE TITLE
Offline Installation

### ISSUE THREAD

**Issue by landge** [stnava/ANTsR#121]
I'm trying to install ANTsR offline on a secured vm connected to a HPC-unit.
The compile process i aborted because the git-request can't reach github.
Thats at least how I interpret this. 
Is there a way to do an offline install with the released tarballs ?
Thanks!
A screenshot (can't copy paste from the vm!)
![screen shot 2016-11-18 at 16 30 50](https://cloud.githubusercontent.com/assets/25629/20435450/6f12eede-adac-11e6-976c-89aa25a9b52b.png)

**Comment by dorianps** [comment]
You could download the zip file and unpack the folder inside it. Rename the
folder to ANTsR and should be the same as using git to get it. Do the same
with ITKR. You can try if the installation works at this point, but you
might need to install other dependencies/packages too, Rcpp in particular.
Have a look at the basic packages needed:

mydeps <- c( "Rcpp", "tools", "methods", "magrittr" )
install.packages( pkgs = mydeps, dependencies = TRUE )

or the full list of dependencies
<https://github.com/stnava/ANTsR/wiki/ANTsR-Dependencies-for-(close-to)-full-functionality>
on the wiki.

Dorian

**Comment by landge** [comment]
Thanks, I've managed to install ITKR, ITK and a lot of the dependencies!
I downloaded the zip, extracted it but I 
![screen shot 2016-11-18 at 17 05 33](https://cloud.githubusercontent.com/assets/25629/20436711/7c9a8e86-adb1-11e6-8d43-734eb7214599.png)
still get the same error ?!

**Comment by stnava** [comment]
you want to install the binary version (if possible) - see the release page
... alternatively, you can put ants in the src directory and build by hand.
 the problem is the failed git clone.


brian

**Comment by landge** [comment]
the binary versions are not compatible with the glibc installed on the system

**Comment by landge** [comment]
ok, I'll try.. thank you

**Comment by stnava** [comment]
not surprising - they are built by travis.


brian

**Comment by cookpa** [comment]
It's not sufficient to have ANTsR and ITKR locally, since they will both attempt to retrieve things from Github (ANTs and ITK respectively).

It might be possible to do an offline install by using a local Git repository. For example, if you have

```
  /path/to/repos/stnava/ANTs.git 
```

locally, you can do

```
git config --global url."/path/to/repos".insteadOf git://github.com
```

But this will have to be done for all the git calls. Normally, ANTsR will get ANTs, ITKR will get ITK. I think ITK also tries to retrieve resources from other git repositories.

If you can build ITK, you can then tell ANTs to use the local ITK instead of cloning. Each ANTs compiles against a specific commit of ITK. If you build ANTs somewhere, you can go to the ITKv4/ directory and type `git status` to see the version that has been checked out.

**Comment by landge** [comment]
I compiled ITK locally and installed ITKR.
After uploading the ANTs source, the compile process started and is still active....

**Comment by landge** [comment]
Do you guys know what that means? 
![screen shot 2016-11-18 at 19 27 38](https://cloud.githubusercontent.com/assets/25629/20441523/253ec436-adc5-11e6-84a9-e9c3c377bdc9.png)

**Comment by stnava** [comment]
do you know if you installed the correct versions of ITK and ANTs?


brian

**Comment by landge** [comment]
No, just took the latest release from each, I think. But I'm not sure. I will check this. Which versions are supposed to work together? 
Thanks

**Comment by stnava** [comment]
see the configuration of both itkr and antsr which give the commits.

this may not be the problem but could be.  alternatively, it could be the
way you configured builds.  basically you should copy the configure scripts
in the packages.


brian

**Comment by landge** [comment]
Thank, you. I'll try that tomorrow!

**Comment by landge** [comment]
It seems that there were some issues with the compilers I loaded via module files on the vm. 
So I started over again just with the default intel-compiler and cmake... , ANTs-2.1.0 and ANTsR_3.3.3.tar.gz, and ITKR with ITK 4.11.
Now, I get this error message: 
<img width="873" alt="screen shot 2016-11-19 at 21 24 34" src="https://cloud.githubusercontent.com/assets/25629/20458235/87ad1a70-ae9f-11e6-9699-45469dc8f7ef.png">
Does this make any sense for you?

**Comment by landge** [comment]
I'm still trying to figure out whats wrong with the installation-process. In a try to solve the above error I compiled version itk-4.10 with the same compiler and settings like everthing else. But the configure script of ANTsR doesn't find the itk.... 
Is there a way to link them together?
<img width="741" alt="screen shot 2016-11-22 at 14 27 54" src="https://cloud.githubusercontent.com/assets/25629/20525515/1a272ec8-b0c0-11e6-8a0b-9e897d6ecca3.png">

**Comment by stnava** [comment]
​you want to copy the configure scripts in both cases - copy them exactly.

https://github.com/stnava/ITKR/blob/master/configure

same for antsr​


brian

**Comment by landge** [comment]
Would like to make one last comment just to round things up.  It turned out that everything (itk, ants, etc.) had to be compiled with the same compiler after downloading the different packages and dependencies. In our case it worked fine with gcc. Once again thanks for your help and sorry for
the late reply.
