### ISSUE TITLE
Bugs with titles in plot.antsImage

### ISSUE THREAD

**Issue by cfhammill** [stnava/ANTsR#123]
There seem to be two small bugs with titles in plot.antsImage

First, if starting with a fresh plot device when using a title you get the error:

```
Error in title(title.img) : plot.new has not been called yet
```

(this may be exclusive to rstudio)

Additionally, with larger slice matrices, the title can be lost behind the slice images.

I believe both problems can be solved by moving the title addition to after drawing the slices.

**Comment by bkandel** [comment]
Could you provide a reproducible example? It would make it much easier to help debug.
