### ISSUE TITLE
install_github("stnava/ITKR") not install in window R

### ISSUE THREAD

**Issue by patelnikit16** [stnava/ANTsR#124]
install_github("stnava/ITKR") when i have install this package in window operating system at  that time below error generate 

`install_github("stnava/ITKR")`
#Downloading GitHub repo stnava/ITKR@master
from URL https://api.github.com/repos/stnava/ITKR/zipball/master
Installing ITKR
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/nikit.patel/AppData/Local/temp/RtmpiUBxDj/devtools121025a515a4/stnava-ITKR-8d84bf1"  \
  --library="C:/Program Files/R/R-3.3.2/library" --install-tests 

#ERROR:  Unix-only package
#* removing 'C:/Program Files/R/R-3.3.2/library/ITKR'
#Error: Command failed (1)

**Comment by stnava** [comment]
please see our specific [windows installations instructions  at the wiki](https://github.com/stnava/ANTsR/wiki/Installing-ANTsR-in-Windows-10-(along-with-FSL,-Rstudio,-Freesurfer,-etc).)

**Comment by patelnikit16** [comment]
thanks sir 

But i have use window 2007 so is it possible on window 2007

**Comment by stnava** [comment]
not possible to install on windows2007 without substantial work on your end


brian
