### ISSUE TITLE
Undocumented functions

### ISSUE THREAD

**Issue by armaneshaghi** [stnava/ANTsR#13]
Trying to complete the documentation for `LabelClustersUniquely`, can anyone confirm my understanding based on the source code:
 - Takes a statistical map (e.g. T map)?
 - Takes a threshold value, based on which clusters are formed
 - Outputs a sequentially re-labeld image based on the thresholded value

Where exactly have you used this before?

**Comment by stnava** [comment]
LabelClustersUniquely should probably be removed - see

?labelClusters

this supersedes LabelClustersUniquely


brian

**Comment by stnava** [comment]
i will handle this b/c it's sensitive


brian
