### ISSUE TITLE
How to make antsRegistration work with doParallel package

### ISSUE THREAD

**Issue by muratmaga** [stnava/ANTsR#133]
Hi folks,

I have a large number of targets that I want to register to a template and save the deformation field. Serially function works fine, but when I invoke doParallel package I receive a memory allocation error, which I presume is due to the template being read in the main session and not get pushed to the workers. 
Is there a way to make this work on a local system (apart from reading the template every time)?

`
doReg=function(X) {
  require(ANTsR)
  mov = antsImageRead( X )
  areg = antsRegistration( tem, mov, typeofTransform = "Similarity")
  areg = antsRegistration( tem, mov, typeofTransform = "SyNOnly",
                         synMetric="CC", synSampling=2, regIterations = c(50, 50, 20),
                         initialTransform = areg$fwdtransforms, verbose = T  )
}
targets=dir(patt="gz")
template=paste(root,"/data/templates/low_res_skull_only.nii.gz",sep="")
tem = antsImageRead( template)

for (i in targets) doReg(i)  #works
cl=makeCluster(4)
registerDoParallel(cl)
foreach (i=targets, .packages='ANTsR') %dopar% doReg(i) #memory allocation error
stopCluster(cl)
`

**Comment by muschellij2** [comment]
Can you see if it works if you read in the template in `doReg`?

**Comment by muratmaga** [comment]
Yep, works fine when I read the template.

**Comment by muschellij2** [comment]
Others can comment about the pointers and such, but for now that's what I'd do (shouldn't take much extra time but isn't efficient).

**Comment by bkandel** [comment]
Have you looked at your computer's CPU usage? Registration should be multithreaded anyway so I doubt you'd see a performance improvement with doParallel.

**Comment by muratmaga** [comment]
There are 40 cores. While registration it's multi threaded, average utilization it's about 40-50%. I figured I would benefit from running multiple streams.
Reading the template inside the function seem to be the most robust solution.
Thanks everyone for the feedback.

Get Outlook for Android


________________________________

**Comment by bkandel** [comment]
I see. That makes sense to me -- because the images in ANTsR are pointers, we have to explicitly clone them (https://github.com/stnava/ANTsR/blob/master/R/antsImageClone.R) instead of just copying them like you would for a regular variable in R.
