### ISSUE TITLE
Determining number of components in SCCAN ?

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#135]
I am starting to use `sparseDecom2` to investigate the relationship between mesial temporal lobe structures and cortical thickness. Is there a way to be empirical in establishing the number of components (nvecs) to use? For example, would it be a good idea to run PCA or ICA on MTL volumes to check how many components are needed to reach, say, 90% of the variance (or, in alternative, eigenvec > 1)?

Dorian

**Comment by stnava** [comment]
setting mycoption = 0 will let you plot the correlations just like you
would with the eigenvalues in the SVD

you can also do that for mycoption = 1 but the meaning is different -
option 0 computes correlations from the residuals ( deflation ) whereas
option 1 does not ... it only uses spatial orthogonality.  so  in that case
you might use a heuristic based on

sparseness = 1.0 / nvecs

which seeks to "cover" the brain.



brian

**Comment by dorianps** [comment]
Thank's, I'll try that.

Before trying that I stumbled in another problem. Right now I am getting thickness values from an (already processed) Freesurfer dataset. Each vertex in the pial surface has a thickness value. Since values are coming from a surface instead of a volume, I can't pass a volumetric `inmask` to allow SCCAN to form clusters with the `cthresh` option. Any idea how to resolve this?

Does it make sense to try to flatten the surface as a bitmap image, then transform that in `antsImage`, and pass that as `inmask` ? Not sure if `sparseDecom2` is ok with getting a 2D mask though...

**Comment by stnava** [comment]
there is a way to handle this .... i can show you (via code) if you send me
10 or more example freesurfer surface (vertex) files ... eg via wetransfer.
 probably something like ten files.  @ntustison ... i will keep you in loop
- it may give us an interesting alternative eval for this other paper.


brian
