### ISSUE TITLE
Usage of ${R_DIR} and ${R_HOME}/bin inconsistent in configure

### ISSUE THREAD

**Issue by dctrud** [stnava/ANTsR#139]
In the top of `configure` `${R_DIR}` is used to find the PATH to Rscript. If this env is set then it needs a trailing slash or the install fails.

```bash
ITKRCMAKE=`${R_DIR}Rscript -e 'a<-ITKR:::itkIncludes(); cat(a)'`
ITKRLIB=`${R_DIR}Rscript -e 'a<-ITKR:::itkLibs(); cat(a)'`
compflags=`${R_DIR}Rscript -e 'a<-ITKR:::itkCompileFlags(); cat(a)'`
ITKDIR=`${R_DIR}Rscript -e 'a<-ITKR:::itkDir(); cat(a)'`
```

Would it be valid to instead use `${R_HOME}/bin/Rscript` here, as is used elsewhere in `configure`, as that should always be set and standard per https://stat.ethz.ch/R-manual/R-devel/library/base/html/EnvVar.html?

**Comment by stnava** [comment]
we would be happy to accept a pull request if you want to try your hand at this repair based on latest git commit
