### ISSUE TITLE
Build issue with ANTsR

### ISSUE THREAD

**Issue by muratmaga** [stnava/ANTsR#145]
Our institute got a new computer system, I am trying to build antsr with R 3.3.3. cmaker, ITKR, ANTsRCore installs fine. ANTsR fails at the very last stage with this message:

installing to /gpfs/home/amaga/R/x86_64-pc-linux-gnu-library/3.3/ANTsR/libs
** R
** data
** inst
** preparing package for lazy loading
Creating a generic function for ‘var’ from package ‘stats’ in package ‘ANTsR’
Creating a generic function for ‘sd’ from package ‘stats’ in package ‘ANTsR’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/gpfs/home/amaga/R/x86_64-pc-linux-gnu-library/3.3/ANTsR/libs/ANTsR.so':
  /gpfs/home/amaga/R/x86_64-pc-linux-gnu-library/3.3/ANTsR/libs/ANTsR.so: undefined symbol: _ZN3itk13ProcessObject8SetInputERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_10DataObjectE
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/gpfs/home/amaga/R/x86_64-pc-linux-gnu-library/3.3/ANTsR’

Any suggestions would be appreciated.

**Comment by stnava** [comment]
can you provide more detail about how you installed?   this usually means you need to run 

```
make clean
```

within the ANTsR directory and reinstall

**Comment by muratmaga** [comment]
I did the git clone repositories
Then
R CMD INSTALL cmaker
R CMD INSTALL ITKR

Etc…
I will try ./cleanup

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by stnava** [comment]
another possibility is that `cmaker` does not provide a  recent enough version of `cmake` 

if this is the case, then you can just install cmake in the environment

**Comment by muratmaga** [comment]
./cleanup fixed the issue. Thanks.

**Comment by muschellij2** [comment]
This should be something to explore with travis builds with ANTsRCore.

**Comment by stnava** [comment]
@muratmaga see above

**Comment by muratmaga** [comment]
Hi Brian,

I did try ./cleanup without any improvement this time. I also made fresh clones of the repository.
