### ISSUE TITLE
maskImage, cropImage issue with segmentations

### ISSUE THREAD

**Issue by muratmaga** [stnava/ANTsR#146]
I have these two images (f original, m a segmentation done outside of ANTsR)  that overlap (verified with plot(f, m)). 
But when I try to use the mask image, it gives an error (below). cropImage returns an empty image.

> m
antsImage
  Pixel Type          : float 
  Components Per Pixel: 1 
  Dimensions          : 177x94x24 
  Voxel Spacing       : 0.351561993360519x0.351561993360519x1.25 
  Origin              : -35.50789 4.185827 25 
  Direction           : 1 0 0 0 -1 0 0 0 1 

> f
antsImage
  Pixel Type          : float 
  Components Per Pixel: 1 
  Dimensions          : 512x512x106 
  Voxel Spacing       : 0.351561993360519x0.351561993360519x1.25 
  Origin              : -90 108.2482 8.75 
  Direction           : 1 0 0 0 -1 0 0 0 1 

> masked=maskImage(img.in = f, img.mask = m, level = 1)
Length of 'mask' vector must be either 0, num-of-voxels-per-time-in-region, num-of-voxels-in-region

**Comment by jeffduda** [comment]
The different origins may be the problem. I believe the images need to
pass: antsImagePhysicalSpaceConsistency(f,m) for the maskImage function to
work.

**Comment by jeffduda** [comment]
actually it's more than just the origin. you'll need to resample one to
match the other via something like f2 = resampleImageToTarget(f,m) or
vice-versa

**Comment by muratmaga** [comment]
Thanks. resampleImagetoTarget() does it.
M

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
