### ISSUE TITLE
Negative sparseness values in sparseDecom2.R

### ISSUE THREAD

**Issue by ntustison** [stnava/ANTsR#147]
Easy question---in Brian's SCCAN tutorial, he often uses negative sparseness values.  What do the negative values signify?  I see the negative value check [here](https://github.com/stnava/ANTs/blob/master/Utilities/antsSCCANObject.h#L787-L797) but in order for that check to be seen, it requires ``doclassic == TRUE`` which is ``FALSE`` by [default](https://github.com/stnava/ANTs/blob/master/Utilities/antsSCCANObject.h#L779).  And I don't see anywhere in [``antsSCCANObject.hxx``](https://github.com/stnava/ANTs/blob/master/Utilities/antsSCCANObject.hxx) where that default value is overridden.

**Comment by stnava** [comment]
i am sure the code is very unclear but *row* sparseness is an experimental concept that is controlled by the `z` parameter.  i have not yet really looked into how to optimize this term ...

the `sparseneness` parameter controls the columns sparseness ... 

in both cases, a *negative* value allows negative entries in the weight vectors .... what i am calling weight vectors would be x,y below in the cca maximization ( just one vector pair here )

argmax_{x,y} x^t X^T Y y  -  s_x \| x \|  -  s_y \|y\|

where s_x and s_y are inversely related to sparseness parameters.

if s_x and s_y are > 0 then we optimize

argmax_{x,y} x^t X^T Y y  -  s_x \| x \|_+  -  s_y \|y\|_+ 

where the norm \| \cdot \|_+  set negative weights to zero

**Comment by ntustison** [comment]
Awesome. Thanks and that makes sense and answers another question I had.
