### ISSUE TITLE
object 'boldMat' not found

### ISSUE THREAD

**Issue by ntustison** [stnava/ANTsR#149]
I'm running ``fmriNormalization.R`` as found in the example as in

```
> library( ANTsR )
> fMRINormalization( verbose = TRUE )
trying URL 'https://ndownloader.figshare.com/files/2119176'
Content type 'binary/octet-stream' length 38175184 bytes (36.4 MB)
==================================================
downloaded 36.4 MB

trying URL 'https://ndownloader.figshare.com/files/2119177'
Content type 'binary/octet-stream' length 4470 bytes
==================================================
downloaded 4470 bytes

trying URL 'https://ndownloader.figshare.com/files/2119178'
Content type 'binary/octet-stream' length 15855 bytes (15 KB)
==================================================
downloaded 15 KB

[1] "polyNuis done"
Error in matrix2timeseries(moco$moco_img, mask, boldMat) : 
  object 'boldMat' not found
```

[Relevant code---](https://github.com/stnava/ANTsR/blob/master/R/powersACTrsfMRIprocessing.R#L205-L227) it seems that since ``fusedImg`` is defined outside the if statement on line 227, should ``boldMat`` on line 208 also be defined prior to the if check?  If so, would be glad to fix it.

**Comment by stnava** [comment]
yeah - putting:

```
  boldMat = timeseries2matrix( moco$moco_img, mask )
```

before 

https://github.com/stnava/ANTsR/blob/master/R/powersACTrsfMRIprocessing.R#L206

would probably fix it

**Comment by ntustison** [comment]
Great.  Thanks.  Checking it right now.

**Comment by ntustison** [comment]
https://github.com/stnava/ANTsR/commit/1262e8b735f07716bb50232c4480c6a0a7b18c27#diff-104794455455967105a7e39128a4484c

and 

https://github.com/stnava/ANTsR/commit/760a5da7ab6431b1e8deeb77b989f046a3b8fde4#diff-104794455455967105a7e39128a4484c
