### ISSUE TITLE
plot antsImage with overlay is wrong

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#15]
The plot of an image with an overlay shows wrong displacement between the two. Initially I thought this is related to a double conversion antsImage->array->antsImage , but now it's clear that is happening in many other situations, perhaps even with original images. Saving the image and loading in itk-snap shows no displacement between images, so this is a specific problem of the plot function.

![image](https://cloud.githubusercontent.com/assets/9083517/6443219/710d655c-c0c3-11e4-94b9-b071ef599118.png)

**Comment by bkandel** [comment]
Can you make a reproducible example and open a bug report?

I might not be able to get to this until Wednesday, but I'll do my best.

2015-03-02 10:04 GMT-05:00 dorianps <notifications@github.com>:

**Comment by bkandel** [comment]
Nevermind about the bug report.

**Comment by bkandel** [comment]
Is it possible the size or spacing of the images is different?

**Comment by bkandel** [comment]
Forget about the example--I think I know what's causing this bug.

**Comment by dorianps** [comment]
Thanks @bkandel . Let me know if you find the solution.

**Comment by bkandel** [comment]
This should be fixed now.  The fix was even easier than I thought.  Try it now and let me know how it looks.

**Comment by dorianps** [comment]
Thanks Ben. Works now.

**Comment by stnava** [comment]
Thanks dudes.
