### ISSUE TITLE
Meaning of fullyConnected argument in labelClusters?

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#150]
I am trying to figure out what does `fullyConnected` mean. The documentation states a cryptic `sets neighborhood connectivity pattern`. It's curious that in ANTsR the input image to `labelClusters` is binarized before being passed to `LabelClustersUniquely`, so my idea that `fullyConnected` might have to do with peaks does not hold.

**Comment by ntustison** [comment]
https://itk.org/Doxygen/html/classitk_1_1ConnectedComponentImageFilter.html#a10cd8bb7182e94019beb55542f6077c7

"Set/Get whether the connected components are defined strictly by face connectivity or by face+edge+vertex connectivity."

**Comment by dorianps** [comment]
Thanks Nick, I am not sure I understand it. I thought this would detect "peninsulas" as different clusters. But in a 2D test, the result is counter-intuitive. Anyone knows why is this happening.

Example 1:
fullyConnected=T -> 1 cluster
fullyConnected=F -> 1 cluster
![image](https://cloud.githubusercontent.com/assets/9083517/25811091/16c82194-33e0-11e7-8d24-d1d7417ee8c2.png)

Example 2:
fullyConnected=T -> 1 cluster
fullyConnected=F -> 2 clusters
![image](https://cloud.githubusercontent.com/assets/9083517/25811150/4d2bf6d4-33e0-11e7-9328-9cf7410deb50.png)

**Comment by ntustison** [comment]
Your examples illustrate the concept.  If a digital object is "fully-connected" then, in 2-D, two foreground pixel neighbors whose edges *or corners* are touching are considered part of the same object. If not fully connected, then only shared edges determine the same object.

**Comment by dorianps** [comment]
Got it. I thought "face+edge+vertex" is an AND condition, but this seem to be an OR condition. Anything touching (face, or edge, or vertex) will consider the parts as a single cluster, if fullyConnected=F.
