### ISSUE TITLE
fMRI tutorial for UVa workshop

### ISSUE THREAD

**Issue by ntustison** [stnava/ANTsR#151]
Hey @dorianps,

You said you were interested in the workshop material and Brian suggested I point you to the WIP [fMRI tutorial](https://github.com/ntustison/ANTsRfMRITutorial) for the event.  Also, [here](https://github.com/stnava/ANTsTutorial/wiki/UVa-Tutorial) are my current notes.

Nick

**Comment by dorianps** [comment]
Thank you.
