### ISSUE TITLE
sigmaVector for smoothing in preprocessfMRI bad format (string should be vector)

### ISSUE THREAD

**Issue by TKoscik** [stnava/ANTsR#152]
Hello,
in the preprocessfMRI function, when smoothing is selected to be "gaussian" the size of the smoothing kernel (e.g., 5) results in the follwoing string being sent to the smoothImage function "5x5x5x0" which then returns an exception:
STD ExceptionObject caught!
Error in .smoothImageHelper(inimg, sigma, sigmaInPhysicalCoordinates,  : 
  not compatible with requested type

the input to smoothImage should be c(5,5,5,0)
line 82 in preprocess fMRI should be:
`sigmaVector <- c(rep(spatialSmoothingParameters[1],3),0)`

**Comment by ntustison** [comment]
Yeah, that was [fixed](https://github.com/stnava/ANTsR/commit/0b971d8c862ddff3c6999ddb9339918af8eba4c9#diff-8de6ca795b058492b666e862741189f5) recently.  Also, you should migrate to ``preprocessRestingBOLD`` as we'll probably deprecate ``preprocessfMRI`` soon.

**Comment by TKoscik** [comment]
thanks.
