### ISSUE TITLE
Can't write files ending in ".img.nii.gz"

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#154]
Not sure if this is a bug or not, but saving files with filenames ending in ".img.nii.gz" changes the filename to ".hdr.gz" and makes the file impossible to read in ANTsR or ITKsnap. Is this a bug (and I would hope so) or is this something we have to live with?

**Comment by stnava** [comment]
that would be an itk issue.  not going to be fixed in antsr.  you could
email itk developers list.


brian

**Comment by dorianps** [comment]
This was indeed a problem in ITK, but they say it's hard to fix. It's caused by trying to establish the file extention immediately after the first period. To me it makes little sense, but it is what it is. Closing issue.
