### ISSUE TITLE
Build/install issues with ANTsR

### ISSUE THREAD

**Issue by snamjoshi** [stnava/ANTsR#179]
I am installing ANTsR on Ubuntu 16.04.2 following the instructions at the install page [here](https://neuroconductor.org/neuroc-help-installing-antsr). 

This is what I have done, in order:

1. Devtools was already installed
2. Ran `which cmake` and `which git`. Got back paths for both.
3. Ran `devtools::install_github( "stnava/ITKR" )` from the R terminal (not GUI). Received message of successful install after build. Not sure how to actually test this though... I can load the package in R but I'm not sure how to tell if there was anything that may have gone wrong.
4. Ran `devtools::install_github( "stnava/ANTsR" )` from the R terminal. It runs all the way to the end (past 100%) and then some other commands are run, finally ending with this:

```
Creating a new generic function for ‘max’ in package ‘ANTsRCore’
Creating a new generic function for ‘min’ in package ‘ANTsRCore’
Creating a new generic function for ‘range’ in package ‘ANTsRCore’
Creating a new generic function for ‘prod’ in package ‘ANTsRCore’
Creating a new generic function for ‘sum’ in package ‘ANTsRCore’
Creating a new generic function for ‘any’ in package ‘ANTsRCore’
Creating a new generic function for ‘all’ in package ‘ANTsRCore’
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘ANTsRCore’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/sanjeev/R/x86_64-pc-linux-gnu-library/3.4/ANTsRCore/libs/ANTsRCore.so':
  /home/sanjeev/R/x86_64-pc-linux-gnu-library/3.4/ANTsRCore/libs/ANTsRCore.so: undefined symbol: gdcmopenjpeg_opj_stream_set_seek_function
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/sanjeev/R/x86_64-pc-linux-gnu-library/3.4/ANTsRCore’
Installation failed: Command failed (1)
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL '/tmp/RtmpNUeH3B/devtools7e3f500b4227/stnava-ANTsR-019df2b'  \
  --library='/home/sanjeev/R/x86_64-pc-linux-gnu-library/3.4' --install-tests 

ERROR: dependency ‘ANTsRCore’ is not available for package ‘ANTsR’
* removing ‘/home/sanjeev/R/x86_64-pc-linux-gnu-library/3.4/ANTsR’
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected!
```
Any ideas what this could mean? All I have tried is updating Rcpp to the newest version. 

The problem is that it takes so long to try out something else since it has to build everything again each time I rerun. So any guidance to at least point me in the right direction or give some suggestions would be helpful! Thanks for all your work.

**Comment by snamjoshi** [comment]
Just saw the thread in [issue #178](https://github.com/stnava/ANTsR/issues/178). I assume this is related? I am also have the undefined symbol issue. Unfortunately, I was not able to follow the discussion in the thread so I'm not sure where to go next.

**Comment by stnava** [comment]
a resolution appears to be in the works via a recent pull request from
@justbennet



brian

**Comment by snamjoshi** [comment]
It compiled and installed just fine for me today. I assume the problem was fixed with ANTsR core? Thanks.
