### ISSUE TITLE
libRcpp breaks with new Rcpp

### ISSUE THREAD

**Issue by muschellij2** [stnava/ANTsR#2]
When I installed using 
library(devtools)
install_github("ANTsR", "stnava")
the install worked fine on MacOSX 10.9.2, R 3.02.

Linux server didn't have CMake so tried the pre-compiled binaries, but didn't work.  Install said it was fine, but when libraried in:

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/bst/student/jmuschel/R/x86_64-unknown-linux-gnu-library/3.0/ANTsR/libs/ANTsR.so':

Which I think is because of my version of Rcpp:
http://cran.r-project.org/web/packages/Rcpp/news.html
"Functions provided/used by Rcpp are now registered with R and instantiated by client package alleviating the new for explicit linking against libRcpp which is therefore no longer created."

**Comment by stnava** [comment]
assuming resolved
