### ISSUE TITLE
Suggested: cropImage 

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#20]
Remove need for reference, just specify slices and axis.

**Comment by bkandel** [comment]
Why shouldn't this be part of cropImage, with a switch depending on whether
the mask is numeric or antsImage?

2015-03-13 12:08 GMT-04:00 stnava <notifications@github.com>:

**Comment by dorianps** [comment]
I m having an issue both with cropImage and cropIndices. All I need is a slice. Both the commands above produce an image with three dimensions, that have a single slice on third dimensions. This causes functions that need a radius to fail (i.e. mrvnrfs). Shouldn't a single slice become a 2D image?

**Comment by ntustison** [comment]
I don't know if this is relevant but those two operations are handled differently in ITK (which I mention since, I believe, the R code in question is based on ITK functions).  The ANTs-based implementation ExtractRegionFromImage is used to crop the image but ExtractSliceFromImage is for what seems to be wanted.

**Comment by stnava** [comment]
yes @ntustison is correct and the current crop behavior is correct.  extractSlice is specific for this case.

**Comment by dorianps** [comment]
Thanks for adding it. There is a small bug:
Error in extractSlice(predlabel, slice.resample, 3)
object 'dimension' not found

**Comment by dorianps** [comment]
extractSlice does not retain header info, sets the direction to diagonal.



**Comment by ntustison** [comment]
> Determining the direction of the collapsed output image from an larger dimensional input space is an ill defined problem in general. It is required that the application developer select the desired transformation strategy for collapsing direction cosigns. It is REQUIRED that a strategy be explicitly requested (i.e. there is no working default). Direction Collapsing Strategies: 1) DirectionCollapseToUnknown(); This is the default and the filter can not run when this is set. The reason is to explicitly force the application developer to define their desired behavior. 1) DirectionCollapseToIdentity(); Output has identity direction no matter what 2) DirectionCollaspeToSubmatrix(); Output direction is the sub-matrix if it is positive definite, else throw an exception.

http://www.itk.org/Doxygen/html/classitk_1_1Testing_1_1ExtractSliceImageFilter.html

**Comment by stnava** [comment]
Yes, if you want to keep the header information you have to use the crop
methods
