### ISSUE TITLE
summary.antsImage function

### ISSUE THREAD

**Issue by bkandel** [stnava/ANTsR#21]
Wrap PrintHeader from ANTs into Rcpp.

**Comment by bkandel** [comment]
What would be useful to have in this function?  What is not present in the antsImage show method that would be useful to have?  Are you interested in all the metadata available from PrintHeader?  That seems like overkill to me...

**Comment by stnava** [comment]
i think that the current show method is fine - but there might be an
extended version that would be similar to PrintHeader


brian
