### ISSUE TITLE
Quiet output needed for ANTsR --- should make verbose=FALSE default in ants functions

### ISSUE THREAD

**Issue by stnava** [stnava/ANTsR#22]
@ntustison - the violators include

* sccan

* antsRegistration

* Atropos

* antsMotionCorr 

* N4BiasFieldCorrection

*  .... anything else?

**Comment by ntustison** [comment]
Off the top of my head, KK will also need to accommodate a verbose flag.  I'll start working on some of the easy ones (N4, KK, Atropos) and then work on antsRegistration.

**Comment by ntustison** [comment]
Hey @stnava , I changed N4

https://github.com/stnava/ANTs/commit/8c58fec34192b5e26007d60f88c3efc23f9bb357

Just to confirm---do we want to make verbose=FALSE by default?  That would be radically different from current behavior.  However, for use inside ANTsR, I'm guessing you could make verbose=FALSE.

**Comment by stnava** [comment]
good question - personally, i think verbose=false would be good in ants as
well .... but we could just implement in antsr ... what do you prefer?


brian

**Comment by stnava** [comment]
we just discussed here and think default behavior should be *not* verbose
.... i.e. like most other software in the world


brian

**Comment by ntustison** [comment]
Okay, I'll do that.

**Comment by ntustison** [comment]
Okay, N4 and KK are complete.  I'm going for a run and will work on the rest sometime later today.

**Comment by ntustison** [comment]
Okay, @stnava , the verbose option has been enabled for

* antsRegistration
* antsApplyTransforms
* KellyKapowski
* N4BiasFieldCorrection
* Atropos

It looks like you hard coded some quieting in antsMotionCorr and I don't know if I'm quite ready to tackle sccan today.  I'll try to look at it tomorrow.  I'm also going to go through some of the scripts and explicitly enable the verbose option as I think they're probably useful in that context.

**Comment by stnava** [comment]
Great!  I'll handle sccan ... that ugliness is mine anyway.

**Comment by ntustison** [comment]
The scripts are done.

**Comment by stnava** [comment]
sccan is, i think, ok now ... wont close this until further testing ....

**Comment by stnava** [comment]
major work is done so closing - will address non-silent output as needed
