### ISSUE TITLE
Add MRIcron as viewer

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#25]
Have a viewer (decided for MRIcron) that can be launched from R to view an antsImage.

**Comment by muschellij2** [comment]
I think you would want to use the standard plot or orthographic views for this and not an external viewer.  This is especially important because you can create reproducible PNGs and PDFs using standard devices and plot().

**Comment by bkandel** [comment]
We already have plot.antsImage, which does basic visualization.  The
motivation for going to an external viewer is the possibility of
interactive viewing of images.  As far as I can tell, there is no way in R
to interact with an image, which makes it difficult to view a 3D image.

2015-03-27 1:24 GMT-04:00 John Muschelli <notifications@github.com>:

**Comment by dorianps** [comment]
Personally, I have changed my mind on the viewer to integrate for quick visualization. I would go with ITKsnap instead of MRIcron. It has better management of layers, colormaps, changes in transparency, etc. If I would be wanting to see an image with an external viewer, it would probably be to use overlays more than just viewing a single image. MRIcron doesn't even allow to unload a single overlay, or to change the order of overlays, or to set specific transparency+colormap options for each overlay. I think the type of user that will be using ANTsR will appreciate more ITKsnap.

**Comment by bkandel** [comment]
I talked about this with Brian, and we decided against adding it to ANTsR.  The main issue is that it introduces an external dependency that will add significant complexity:  Maintenance of interface, ability to control the spawned process from R, etc., so it would go too far afield from the core purpose of ANTsR, which is to provide reproducible R-based processing of images. 

If you wanted to do this on your own machine, a sample script would look something like: 

```r

itksnap <- function(image, overlay=NA) { 
  tempname1 <- paste(tempfile(), '.nii.gz', sep='')
  antsImageWrite(image, tempname1)
  command <- paste('itksnap -g', tempname1)
  if (!is.na(overlay)) {
    tempname2 <- paste(tempfile(), '.nii.gz', sep='')
    antsImageWrite(overlay, tempname2)
    command <- paste(command, '-o', tempname2)
  }
  system(command)
}
```
You could expand this by adding support for multiple overlays, segmentations, etc.

**Comment by stnava** [comment]
thanks @bkandel


brian

**Comment by dorianps** [comment]
As we talked, Shiny can now be used for a similar purpose. Simple interaction with three views.

**Comment by bkandel** [comment]
Yes!  That would be better.  If you are able to put up a general-purpose
function, that would be helpful.

2015-06-10 16:28 GMT-04:00 dorianps <notifications@github.com>:

**Comment by stnava** [comment]
agreed - would be nice to have that documented somewhere ... i recall
sending an example but doubt it's archived appropriately


brian

**Comment by muschellij2** [comment]
Just FYI - We have tried this to some degree.  

You can try papayar (https://github.com/muschellij2/papayar), which is based on Papaya/Mango (https://github.com/rii-mango/Papaya/).

```{r}
devtools::install_github("muschellij2/papayar")
library(papayar)
URL <- "http://nifti.nimh.nih.gov/nifti-1/data/zstat1.nii.gz"
urlfile <- file.path(tempdir(), "zstat1.nii.gz")
download.file(URL, dest=urlfile, quiet=TRUE)
papaya(urlfile)
```

Then if you change the windowing to [0, 10] and see the image.

You can also use `itksnapr` (https://github.com/muschellij2/itksnapr):
```{r}
devtools::install_github("muschellij2/itksnapr")
library(itksnapr)
URL <- "http://nifti.nimh.nih.gov/nifti-1/data/zstat1.nii.gz"
urlfile <- file.path(tempdir(), "zstat1.nii.gz")
download.file(URL, dest=urlfile, quiet=TRUE)
itksnap(urlfile)
```

**Comment by dorianps** [comment]
Papaya did not work for me in the cluter, requires safari which is not there.

ITKsnap solution looks great and worked right away. It just needs a tiny change to accept antsImage class. If input is antsImage, save it to temp folder, then call itksnap. I would also suggest to keep -g background and -o overlays as separate arguments.

Thank you.
