### ISSUE TITLE
Creating another mirror-repo for ANTsR check test

### ISSUE THREAD

**Issue by armaneshaghi** [stnava/ANTsR#27]
to run tests in a different repo

**Comment by bkandel** [comment]
Were you going to do this?

**Comment by bkandel** [comment]
If not, I can do it.

**Comment by armaneshaghi** [comment]
yes please, i think it would be better you or brian do this, and then you can add others as collaborators.

**Comment by armaneshaghi** [comment]
@bkandel forgot to add that whoever opens the new repo has to register in travis, and get the travis coverage testing logo. thanks

**Comment by bkandel** [comment]
OK, will do.  Not sure I'll get to it today though--fixing plot.antsImage
is higher priority right now.

2015-03-13 16:00 GMT-04:00 Arman Eshaghi <notifications@github.com>:

**Comment by bkandel** [comment]
New branch rcmdcheck should take care of this.
