### ISSUE TITLE
antsImage.cpp:6:10: fatal error: 'itkAddImageFilter.h' file not found

### ISSUE THREAD

**Issue by cookpa** [stnava/ANTsR#29]
Started getting this earlier today on the master branch. But the file seems to exist

src/itkb/itkinst/include/ITK-4.8/itkAddImageFilter.h
src/itks/Modules/Filtering/ImageIntensity/include/itkAddImageFilter.h

Still, R CMD INSTALL ANTsR quickly fails with

antsImage.cpp:6:10: fatal error: 'itkAddImageFilter.h' file not found
#include "itkAddImageFilter.h"
         ^
1 error generated.
make: *** [antsImage.o] Error 1
ERROR: compilation failed for package ‘ANTsR’
* removing ‘/Users/pcook/Library/R/3.1/library/ANTsR’
* restoring previous ‘/Users/pcook/Library/R/3.1/library/ANTsR’

**Comment by stnava** [comment]
When did you pull? Os?

See website for status of builds

**Comment by cookpa** [comment]
OS X 10.9, up to date with current HEAD

**Comment by bkandel** [comment]
I got this also. Clean clone fixed it.

2015-03-16 14:59 GMT-04:00 Philip Cook <notifications@github.com>:

**Comment by stnava** [comment]
yes ,,, you are not up to date


brian
