### ISSUE TITLE
small bug when plotting empty images

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#31]
> predlabel2 = predlabel*0
> plot(predlabel2)
Error in if (window.img[1] == window.img[2]) window.img[1] <- min(x) : 
  missing value where TRUE/FALSE needed

**Comment by bkandel** [comment]
Ah, yes, that makes sense. It probably depends on how R computes quantiles
of a totally uniform distribution.  We can correct this.

2015-03-18 16:50 GMT-04:00 dorianps <notifications@github.com>:

**Comment by dorianps** [comment]
Since we are here, you may want to add something that checks if images is a label images, like
length(labels(as.factor(as.array(img))))<10

and keep the window 0 to max.
Some labels don't appear with automatic windowing. Problem is that the code above is kind of slow.

**Comment by bkandel** [comment]
We should have better support for labeling anyway.  We currently assume the
overlay is basically continuous; if we deal with labels correctly, we
should have a specific list of colors, not a heatmap-type visualization.

2015-03-18 16:57 GMT-04:00 dorianps <notifications@github.com>:

**Comment by dorianps** [comment]
Yeap, need to make 0 value transparent on overlay.

Also, alpha setting still doesn't work (compiled yesterday at 4pm).

**Comment by bkandel** [comment]
Fixed this issue.  As for the labels:  Setting the window.overlay to the max and min values of the labels and setting the colorbar to "rainbow" should work pretty well.
