### ISSUE TITLE
%>% not working with multiplicate or divide

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#32]
works with + or -
temp = ConAvgDiff.t1[[k]] %>% iMath('Normalize') %>% - brainmask

doesn't work with * and /
temp = ConAvgDiff.t1[[k]] %>% iMath('Normalize') %>% * brainmask
Error: unexpected '*' in "temp = ConAvgDiff.t1[[k]] %>% iMath('Normalize') %>% *"

**Comment by dorianps** [comment]
Never mind,
Subtraction/addition needs %>% before.
Division/multiplication works without %>%.

A bit confusing but at least works.

**Comment by bkandel** [comment]
I'm not sure what you mean, but concatenating multiple atomic arithmetic
operators works just like in normal math:
> r16 <- antsImageRead(getANTsRData('r16'))
> mysum <- r16 + r16 + r16
> mydiv <- r16 / r16 / r16
works as expected, with no need for special piping ("%>%").

2015-03-21 18:24 GMT-04:00 dorianps <notifications@github.com>:

**Comment by bkandel** [comment]
I would use parentheses to make sure you're getting what you think you're
getting.

2015-03-21 21:10 GMT-04:00 Ben Kandel <ben.kandel@sbcglobal.net>:
