### ISSUE TITLE
Can't use multiple cores

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#33]
This is a really weird error. I want to use foreach loops with multiple processors. If I run a single loop I can capture the output and everything is fine. If I use more than one loop, the output is corrupt and R crashes. Here is the example:

img1 = antsImageRead(getANTsRData('r16'), 2)
img2 = antsImageRead(getANTsRData('r27'), 2)
temp=list(img1,img2)
  
library(foreach)  
library(doMC)  
registerDoMC(2)

  #### single loop  
output = foreach(i=1:1) %dopar% {  
  kmeansSegmentation(temp[[i]], 3, getMask(temp[[i]]))$segmentation  
}  

> output
[[1]]
antsImage
  Pixel Type   : float 
  Pixel Size   :  
  Dimensions   : 256x256 
  Voxel Spacing: 1x1 
  Origin       : 0 0 
  Direction    : 1 0 0 1 

plot(output[[1]])
![image](https://cloud.githubusercontent.com/assets/9083517/6790639/85872f0a-d17f-11e4-9ea2-319047d26c65.png)

  #### two loops  
output = foreach(i=1:2) %dopar% {  
  kmeansSegmentation(temp[[i]], 3, getMask(temp[[i]]))$segmentation
}

> output
[[1]]
antsImage
  Pixel Type   : float 
  Pixel Size   :  

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call("antsImage_dim", x, PACKAGE = "ANTsR")
 2: dim(object)
 3: dim(object)
 4: paste(dim(object), collapse = "x")
 5: cat("  Dimensions   :", paste(dim(object), collapse = "x"), "\n")
 6: function (object) standardGeneric("show")(<S4 object of class "antsImage">)
 7: function (object) standardGeneric("show")(<S4 object of class "antsImage">)
 8: print.default(<S4 object of class "antsImage">)
 9: print(<S4 object of class "antsImage">)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

**Comment by dorianps** [comment]
More info:
This is happening in CFN cluster, after qloginp2 (two processing cores requested)

**Comment by bkandel** [comment]
Using multiple cores with foreach is a bit tricky.  You may have to read
the images you want in to each core before you try to process the
images--there is no guarantee that it will take your environment variables
as you would expect.

There should in general be no need to do this, though.  ANTsR relies on
ITK's multithreading capabilities, which should give you multi-core
capabilities invisibly.

2015-03-23 17:16 GMT-04:00 dorianps <notifications@github.com>:

**Comment by dorianps** [comment]
What is the best test to check whether itk is really using multiple threads?

**Comment by stnava** [comment]
https://www.google.com/search?q=ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS&oq=ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS&aqs=chrome..69i57.8519j0j4&sourceid=chrome&es_sm=119&ie=UTF-8

some info in above

you can check top to see n-threads


brian

**Comment by bkandel** [comment]
If you're using this on the cluster, the ITK global threads option is set
as you start the qlogin session.


2015-03-23 17:51 GMT-04:00 stnava <notifications@github.com>:
