### ISSUE TITLE
Operators for antsImage

### ISSUE THREAD

**Issue by muschellij2** [stnava/ANTsR#34]
I don't want to add this as a direct pool request as it may break some code already, but I think you want do this for Ops in general (or at least Arith, Math, and Summary)
https://github.com/muschellij2/ANTsR/blob/master/R/antsImage_Operators.R

I'm not clear as to how you store logicals, and these may cause some problems.  It is not as flexible as the operators you've implemented in that you cannot pass the … into as.antsImage (such as mask), but I think that can be added.

Also, you may want to define:
is.antsImage <- function(x){
  inherits(x, 'antsImage')
}
or simply:
is.antsImage <- function(x){
  is(x, 'antsImage')
}
in case someone extends your class.

**Comment by bkandel** [comment]
Interesting.  I am a bit hesitant to allow functions that we haven't
explicitly defined, though.  In other words, if someone tries to do some
generic function that we haven't implemented for antsImages, I'd want the
error to be "no method blahblah for class antsImage."  If we do this, it
could silently give unexpected results.  I'm not sure about this, though,
and if anyone else has ideas I'd be interested in hearing.

Good idea for the inheritance.  I'll change that.

2015-03-23 20:17 GMT-04:00 John Muschelli <notifications@github.com>:

**Comment by muschellij2** [comment]
I agree - you have pretty much implemented Arith and parts of math/summary.
  for example, you would take out +.antsImage, and %%.antsImage and the
rest, and implementing through Arith.  The main reason I like this method
because if some check needs to be implemented, then it's in one spot.  So
maybe I'm suggesting Arith and not Ops.

I agree, though, that some might not be so straightforward (for example
cumsum).

From ?Ops:

Arith

"+", "-", "*", "^", "%%", "%/%", "/"

Compare

"==", ">", "<", "!=", "<=", ">="

Logic

"&", "|".

Ops

"Arith", "Compare", "Logic"

Math

"abs", "sign", "sqrt", "ceiling", "floor", "trunc", "cummax", "cummin",
"cumprod", "cumsum", "log", "log10", "log2", "log1p", "acos", "acosh",
"asin", "asinh", "atan", "atanh", "exp", "expm1", "cos", "cosh", "cospi",
"sin", "sinh", "sinpi", "tan", "tanh", "tanpi", "gamma", "lgamma", "digamma",
"trigamma"

Math2

"round", "signif"

Summary

"max", "min", "range", "prod", "sum", "any", "all"

Complex

"Arg", "Conj", "Im", "Mod", "Re"

**Comment by stnava** [comment]
resolved with recent work
