### ISSUE TITLE
antsAverageImages error

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#35]
It doesn't seem the variable "template" is needed for anything.

average = antsAverageImages(trn.imgCon, normalize = T)
Error: object 'template' not found

function (imageList, normalize = FALSE) 
{
    avg <- imageList[[1]] * 0
    for (i in imageList) {
        if (normalize) {
            i <- i/mean(i)
        }
        template <- template + i
    }
    avg <- avg/length(imageList)
    return(avg)
}
<environment: namespace:ANTsR>

**Comment by dorianps** [comment]
Corrected:

antsAverageImages = function (imageList, normalize = FALSE) 
{
  avg <- imageList[[1]] * 0
  for (i in imageList) {
    if (normalize) {
      i <- i/mean(i)
    }
    avg <- avg + i
  }
  avg <- avg/length(imageList)
  return(avg)
}

**Comment by bkandel** [comment]
If the help file for this function had a reproducible example, this bug would have been caught automatically by Travis.

**Comment by stnava** [comment]
agreed - the example should be added


brian

**Comment by dorianps** [comment]
Normalization step was missing in fix above:

antsAverageImages = function (imageList, normalize = FALSE) 
{
  avg <- imageList[[1]] * 0
  for (i in imageList) {
    if (normalize) {
      i <- i/mean(i)
    }
    avg <- avg + i
  }
  avg <- avg/length(imageList)
  if (normalize) avg = avg %>% iMath('Normalize')
  return(avg)
}

**Comment by bkandel** [comment]
The fix I pushed took care of this: https://github.com/stnava/ANTsR/commit/3e97beb63f22452fde84f20223a125053b8b133e

**Comment by dorianps** [comment]
Good, cause mine above is not good enough, needed another fix.
