### ISSUE TITLE
Suggested: add step parameter or manually define layers in getNeighborhoodInMask

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#36]
One of the biggest issues when working with 1mm images is the huge matrix size obtained from a full brain 1mm neighborhood matrix with radius 4. The matrix can be 16gb or more.

To my understanding, with higher resolution the neaghboring voxels are increasingly less informative. What I need is not the immediate surrounding voxel layers but further out. The best would be to get i.e. 1st neighrbohood layer, 3rd layer, etc, thus skipping some neighborhood layers.

Would be great if this is achieved with a "step" parameter, or better if can be defined manually, like c(1,3,4) to get 1st layer + 3rd layer + 4th layer.

Let me know if this is not clear.

**Comment by stnava** [comment]
you are requesting a new function `getShapedNeighborhoodMatrix`.   someone may eventually implement such a thing but i doubt soon.

**Comment by stnava** [comment]
@jeffduda did what is reasonable for this.
