### ISSUE TITLE
makeImage != antsImageRead = antsImageWrite

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#39]
An aesthetic issue:
Perhaps would be better to have consistent name for make, read, and write image. Maybe is better to have makeImage, readImage, writeImage.

**Comment by bkandel** [comment]
We had decided that changing the antsImageRead function name would be too
big a break, because it would break everyone's code for everything.  The
ideal solution would be to have read.antsImage, write.antsImage, and
make.antsImage (?), because that's the R standard for naming these sorts of
things.  We could implement those and have a deprecation warning.

2015-03-26 14:02 GMT-04:00 dorianps <notifications@github.com>:

**Comment by stnava** [comment]
i'd be fine with this - but lots of code would break ... e.g. any of these
that have to do with antsr:

http://rpubs.com/stnava/ANTsTut




brian

**Comment by dorianps** [comment]
Ah, ok never mind. I was thinking shorter is better, write.antsImage is even longer that current one.

To be perfectly honest, all these upper/lowercase alternations are already annoying when coding, adding other characters to it makes it even more complex.

**Comment by stnava** [comment]
http://en.wikipedia.org/wiki/CamelCase


brian

**Comment by bkandel** [comment]
read.ai / write.ai ?

2015-03-26 14:12 GMT-04:00 stnava <notifications@github.com>:

**Comment by stnava** [comment]
this type of question has come up several times ....

if we are going to make a big break with (inconsistent) past
implementation, might as well redo

the whole toolkit to maximize consistency.




brian

**Comment by bkandel** [comment]
True.  Also tab completion is your friend.

2015-03-26 14:29 GMT-04:00 stnava <notifications@github.com>:

> this type of question has come up several times ....
>
> if we are going to make a big break with (inconsistent) past
> implementation, might as well redo
>
> the whole toolkit to maximize consistency.
>
>
>
>
> brian
>
>

**Comment by bkandel** [comment]
I'm going to close this as an issue.  We may revisit this in the future as part of a major refactoring attempt, but it is not likely to happen in the near future.
