### ISSUE TITLE
cropImage - wrong number of slices

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#42]
@bkandel thought this is bug.

I have a crop mask with 7 slices (83:89), but crop is producing an image with 8 slices.

Get file here:
https://www.dropbox.com/s/ot4ponqk7j221n6/templateBrainMask.nii.gz?dl=0

Run:
brainmask=antsImageRead('templateBrainMask.nii.gz',3)
cropmask=brainmask*0
cropmask[1:192,1:256, 83:89] = 1
cropImage(brainmask,cropmask)
antsImage
  Pixel Type   : float 
  Pixel Size   :  
  Dimensions   : 192x256x8 
  Voxel Spacing: 0.9765625x0.9765625x1 
  Origin       : -93 138.1172 1 
  Direction    : 1 0 0 0 -1 0 0 0 1

**Comment by stnava** [comment]
may be a bug but it's not in `cropImage`.  look (visually) at 

```
brainmask=antsImageRead('templateBrainMask.nii.gz',3)
cropmask=brainmask*0
cropmask[1:192,1:256, 83:89] = 1
antsImageWrite( cropmask, "temp.nii.gz" ) 
```
and also

```
brainmask=antsImageRead('templateBrainMask.nii.gz',3)
cropmask=brainmask*0
cropmask[1:191,1:255, 83:89] = 1
cropImage(brainmask,cropmask)
```

off by one error somewhere ... i've looked at this before but havent identified the problem.

**Comment by dorianps** [comment]
cropIndices works fine

Would decropImage work for images cropped with cropIndices?

**Comment by stnava** [comment]
again - this is the location of the issue

```
cropmask[1:192,1:256, 83:89] = 1
````

which , if you look at the resulting image, is not what you expect.  has nothing to do with cropImage.

if someone wants to resolve this, then recommend opening another issue that has to do with indexing.

unfortunately, i wont have time to look at this ... possibly until august.

**Comment by dorianps** [comment]
Yes, it seems the assignment is off. It's assigning slices 84:90.
cropmask[1:192,1:256, 83:89] = 1
plot(cropmask, axis=3, slices=82:90)   # should show two black slices on the sides, but it doesn't
plot(cropmask, axis=3, slices=83:91)  # this shows two black slices on the sides

**Comment by stnava** [comment]
right - so open a new issue that identifies the problem more clearly and assign to @jeffduda

**Comment by dorianps** [comment]
Ok.

I don't see how this would affect cropImage though. There are still 7 slices in cropimage (albeit displaced), but cropImage produces 8.

**Comment by stnava** [comment]
that is not correct.  there are 8 slices with non-zero entries and
cropImage is just following the garbage that is being put in.  please see
the example that i gave you in my first response.


brian
