### ISSUE TITLE
Wrong subsetting assignment

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#43]
@jeffduda 
Issue emerged here: https://github.com/stnava/ANTsR/issues/42

Problem: assigning is performed on wrong slices, and may also contaminate other dimensions

Example:
3D file: https://www.dropbox.com/s/ot4ponqk7j221n6/templateBrainMask.nii.gz?dl=0

brainmask=antsImageRead('templateBrainMask.nii.gz',3)
cropmask=brainmask*0
cropmask[1:192,1:256, 83:89] = 1
plot(cropmask, axis=3, slices=82:90)  # should show two black slices on the sides, but it doesn't
plot(cropmask, axis=3, slices=83:91)  # this shows two black slices on the sides

Plus cropImage thinks there are 8 slices with some value = 1.
cropImage(brainmask,cropmask)
antsImage
Pixel Type : float 
Pixel Size :  
Dimensions : 192x256x8 
Voxel Spacing: 0.9765625x0.9765625x1 
Origin : -93 138.1172 1 
Direction : 1 0 0 0 -1 0 0 0 1

**Comment by stnava** [comment]
@jeffduda  - to clarify, this is an off by one error in the subsetting implementation ... the last+1 indexed slice has a single row of 1s.  the first indexed slice has a single row of zeroes.

has nothing to do with cropImage - that is a red herring.

**Comment by jeffduda** [comment]
definitely something odd going on with setting values via [] operators. Issue may be easily viewed with:
img = as.antsImage( array( data=0, dim=c(4,4,8) ) )
img[1:4,1:4,4:6]= 1
img[,,1:8]

**Comment by stnava** [comment]
right - for comparison see

img = as.antsImage( array( data=0, dim=c(4,4,8) ) )
img[0:4,0:4,4:6]= 1
img[,,1:8]



brian

**Comment by jeffduda** [comment]
to be clear, should the below even work?
img[0:4,0:4,4:6]= 1

I was under the impression the [] operator should use R-style 1-based indices

**Comment by stnava** [comment]
it shouldnt work - but it does and gives closer to "the right" behavior ...
point is there is (at least one) off by one error or some inconsistency in
implementation.




brian

**Comment by jeffduda** [comment]
I see, 
img2[0:3,0:3,4:6]= 1
gives "closest" results. All values set within slices, slices off by 1 index

**Comment by stnava** [comment]
good - should be easy to fix, hopefully.


brian

**Comment by bkandel** [comment]
As long as you're taking a look at this, it would be great if you could try
to see if you can get missing indices to work, as in img[, , 1] <- 1.  I
couldn't figure out how to do it, but I imagine it's possible to modify the
antsImage_SetRegion command to deal with missing indices.

2015-03-31 14:39 GMT-04:00 stnava <notifications@github.com>:

**Comment by jeffduda** [comment]
At first glance, it appears the missing indices were only implemented for the first two dimension, so once the other issue is resolved, this should be an easy addition.

**Comment by dorianps** [comment]
Confirm. Missing indices worked for first two dimensions, failed for third.

**Comment by bkandel** [comment]
It's tricky because only the first two arguments of "[" are named.  If you
figure out how to do it, though, that would be great.

2015-03-31 15:07 GMT-04:00 dorianps <notifications@github.com>:

**Comment by jeffduda** [comment]
Going to add some error checking, etc to help prevent unintended behavior on invalid input, but should now work "as expected" for valid input.

**Comment by stnava** [comment]
many thanks, jeff!


brian

**Comment by stnava** [comment]
@jeffduda can you check https://travis-ci.org/stnava/ANTsR after builds?  the latest stuff broke the R CMD check  (no idea why, possibly documentation issues?) --- i added a cat of the install.out and check.log to help provide insight into build failures.
