### ISSUE TITLE
Re-add -DVCL_CAN_STATIC_CONST_INIT_FLOAT=0  to src/Makevars

### ISSUE THREAD

**Issue by zarquon42b** [stnava/ANTsR#44]
Hi,
after your recent revamp, "-DVCL_CAN_STATIC_CONST_INIT_FLOAT=0" was dropped from 
-PKG_CPPFLAGS. With this option added, everything builds fine again.
This requires to throw in an -fpermissive flag. Could you please readd this, or is there a reason for dropping it? 

Best
Stefan

**Comment by stnava** [comment]
https://github.com/stnava/ANTsR/blob/master/src/Makevars

It should be there,  no?

**Comment by zarquon42b** [comment]
Ahem, sorry forgot to pull.
