### ISSUE TITLE
WISH: Add antsApplyTransformsToPoints to ANTsR

### ISSUE THREAD

**Issue by zarquon42b** [stnava/ANTsR#45]
Hi,
as I am mostly dealing with Volume and surface data, I momentarily am using a wrapper called [antsTransformPoints*](https://github.com/zarquon42b/RANTs/blob/master/R/newAntsExample.r#L45) (it is an S3 function) calling the command line tool antsApplyTransformsToPoints to apply the transforms to point sets. It takes care of IJK to RAS transform and works on matrices and meshes of class "mesh3d". Would it be a big issue to implement this in ANTsR?

*) vert2points used from Morpho is simply 
```r
vert2points  <- function (mesh) {
    out <- t(mesh$vb[1:3, ])
    return(out)
}

```

Best
Stefan

**Comment by stnava** [comment]
I am in agreement about this and put it on the to do list.

**Comment by jefferis** [comment]
Incidentally, @zarquon42b, have you looked at my [NeuroAnatomy Toolbox](https://github.com/jefferis/nat) which needs to handle similar kinds of functionality (transforming points, surfaces, linesets and also volumes) – presently only for the [CMTK registration suite](nitrc.org/projects/cmtk/)  but I hope to provide ANTs support (via ANTsR) in due course.

For example there is an `xform` generic to handle transformation of 3d data using registrations, with methods for a few specific cases. The generics for objects are essentially all the same, see:

https://github.com/jefferis/nat/blob/master/R/xform.R#L63-L78

and rely on two helper functions, `xyzmatrix` and `xyzmatrix<-` which are used to get and set vertex information for a variety of types with 3d vertices. For `rgl::mesh3d` objects (which have a base class `shape3d`), I have done this via

```r
# get
xyzmatrix.shape3d<-function(x, ...){
  cbind(x$vb[1, ]/x$vb[4, ], x$vb[2, ]/x$vb[4, ], x$vb[3, ]/x$vb[4, ])
}

# set
`xyzmatrix<-.shape3d`<-function(x, value){
  x$vb=t(cbind(value, 1))
  x
}
```

I would be interested to see if we can learn anything from our respective implementations.

Best wishes,

Greg.

**Comment by zarquon42b** [comment]
Hi @jefferis , thanks for the tips, I only had a peak at your package but will look closer. Up until now my own work is mostly based on 3d-point sets (landmarks) and triangular meshes. I have implemented a simple way to compute rigid, affine, similarity and tps deforms for meshes/points based on landmark transforms in [computeTransform](https://github.com/zarquon42b/Morpho/blob/master/R/ComputeTransform.r) and [applyTransform](https://github.com/zarquon42b/Morpho/blob/master/R/applyTransform.r), as well as some elastic and non-elastic icp in my inofficial package [mesheR](https://github.com/zarquon42b/mesheR).

Best
Stefan

**Comment by stnava** [comment]
this is now added to antsr ... the behavior is consistent with [the chicken example](https://github.com/stnava/chicken) ... i am leaving this issue open in case there is further discussion wrt IJK to RAS or other cases.  the basic idea of aatxtp is to transform the first d coordinates and carry along any other information beyond dimension d.

**Comment by stnava** [comment]
@zarquon42b - added a more detailed example here that may help clarify transformation standards https://github.com/stnava/ANTsR/commit/334b52f8e1c837a1532da692ec645a37a08c0646

**Comment by stnava** [comment]
assuming this is working well .... so closing.
