### ISSUE TITLE
R 3.2 ANTsR Failures 4/29/2015

### ISSUE THREAD

**Issue by stnava** [stnava/ANTsR#47]
this is from R 3.2 

## Examples

... to test examples by themselves, do the following

cd ANTsR  # source dir
ln -s inst/extdata . 
R
devtools::run_examples() 

when you are done, be sure to remove the linked ext data

current findings:

* aslPerfusion reports "exception caught"

* iMathOps.Rd fails on several examples ... i fixed a couple but had to comment 
  k  <- eval( parse( text = toString( iMathOps$Example[j] ) ) )
due to unclear BlobDetector failure ... this really needs to be fixed
```
 i<-antsImageRead( getANTsRData('r16') , 2 )
 iMath(i,"BlobDetector",100)
```

*  basic erosion and dilation fails  
```
img<-antsImageRead( getANTsRData("r16"))
 mask<-getMask( img )
 mask2<-getMask( img )
 mask<-iMath(mask,'ME',25)
print(paste( sum(mask2==1), sum(mask==1) ))
```
i added a test for this in iMathOps ...

## Vignettes

seem to be ok .... though i did not look at the results visually.  they at least build.

## Documentation issues

* checking R code for possible problems ... NOTE
aslCensoring : robSelection: no visible binding for global variable
  â€˜mask_imgâ€™
aslCensoring : robSelection: no visible binding for global variable
  â€˜dorobustâ€™
aslCensoring: no visible binding for global variable â€˜matâ€™

* checking for missing documentation entries ... WARNING
Undocumented code objects:
  %>%

this last issue was resolved with an Imath documentation object

but this was removed for unknown reasons ... i undid this here:

https://github.com/stnava/ANTsR/commit/2460a414b36426c91e3f2d899a38197e3668a1a0

so as not to avoid the variety of things that were breaking.

**Comment by stnava** [comment]
@jeffduda  see comments in this issue .... if you want to continue with the iMath business, please make sure changes are backward compatible ... i.e. keep iBind and %>% documentation and other things in iMath working.

**Comment by bkandel** [comment]
I fixed the issues in aslCensoring.

**Comment by bkandel** [comment]
Currently seeing: 
> ### Name: antsSpatialICAfMRI
> ### Title: Perform spatial ICA on fMRI bold data.
> ### Aliases: antsSpatialICAfMRI
>
> ### ** Examples
>
> set.seed( 123 )
> boldImages <- list()
> n=16
> nvox <- n*n*n*12
> dims <- c(n,n,n,12)
> boldImages[[1]] <- makeImage( dims , rnorm( nvox )+500 ) %>% iMath("PadImage" , 4 )
> boldImages[[2]] <- makeImage( dims , rnorm( nvox )+500 ) %>% iMath("PadImage" , 4 )
> boldImages[[3]] <- makeImage( dims , rnorm( nvox )+500 ) %>% iMath("PadImage" , 4 )
>
> cleanBoldImages <- list()
> for( i in 1:length( boldImages ) )
+   {
+   fmri <- preprocessfMRI( boldImages[[i]], residualizeMatrix=FALSE )
+   if( i == 1 ) maskImage <- fmri$maskImage
+   cleanBoldImages[[i]] <- fmri$cleanBoldImage
+   }
>
> icaResults <- antsSpatialICAfMRI( cleanBoldImages, maskImage,
+   numberOfICAComponents = 2 )
Error in svd(scale(x %*% t(x))) : infinite or missing values in 'x'
Calls: antsSpatialICAfMRI -> whiten -> svd
Execution halted

**Comment by stnava** [comment]
yes - tried to fi that yesterday --- somewhat platform/run specific ... problem is `preprocessfMRI` now returns some junk (all zero)  images ... not sure why.

**Comment by stnava** [comment]
ok this `antsSpatialICAfMRI ` issue is fixed now

**Comment by bkandel** [comment]
Currently aslDenoiseR example still fails.

**Comment by bkandel** [comment]
These all appear to be fixed now, so closing.
