### ISSUE TITLE
How to get a transformation matrix from .mat files

### ISSUE THREAD

**Issue by zarquon42b** [stnava/ANTsR#50]
Hi, I am trying to get the affine transformation from a .mat file. I can import them via ```R.matlab::readMat()``` and get a list containing ```$AffineTransform.float.3.3``` (a 12x1 matrix) and a 3x1 matrix named ```$fixed```. Is there an easy way to combine this to a transform matrix (4x4 in my case)?
It looks like this:
```r
$AffineTransform.float.3.3
               [,1]
 [1,]    1.05657983
 [2,]    0.04566867
 [3,]    0.03638180
 [4,]   -0.04745625
 [5,]    0.99157244
 [6,]   -0.15884599
 [7,]   -0.01750578
 [8,]    0.08629224
 [9,]    1.02625072
[10,]   -3.50945663
[11,] -185.69580078
[12,]  777.48010254

$fixed
              [,1]
[1,]    -1.3779984
[2,]     0.2889023
[3,] -1098.2500000

attr(,"header")
attr(,"header")$version
[1] "4"

attr(,"header")$endian
[1] "little"
```

The correct affine matrix (calculated from deformed pointsets using ```Morpho::computeTransform()```) would be: 
```r
[1,]  1.05657998  0.04566868 -0.03638175 -36.51162
[2,] -0.04745618  0.99157235  0.15884597 360.21133
[3,]  0.01750584 -0.08629226  1.02625079 806.26085
[4,]  0.00000000  0.00000000  0.00000000   1.00000
```
of which the upper-left 3x3 submatrix is (apart from the sign) equivalent to ```matrix(mat$AffineTransform.float.3.3[1:9],3,3,byrow = T)```

Thanks 
Stefan

**Comment by stnava** [comment]
should be

[ x_1 x_2 x_3
  x_4 x_5 x_6
  x_7 x_8 x_9 ]

+ translation

fixed is the center of transformation .... all in ITK coordinates.




brian

**Comment by zarquon42b** [comment]
Hi,
thanks a lot. I assume the way to do this is the following:
be ```centermat``` the 4x4 matrix that translates the data by ```-fixed```, ```affine``` the affine matrix
and ```translate``` doing the final translation then the resulting transform should be 

```r
translate %*% solve(centermat) %*% affine %*% centermat
```
This gives me the exact same coefficients, however when comparing the signs to the "true" 4x4 transformation matrix, I get the following pattern: 
```r
     [,1] [,2] [,3] [,4]
[1,]    1    1   -1   -1
[2,]    1    1   -1   -1
[3,]   -1   -1    1    1
[4,]  NaN  NaN  NaN    1

```
The NaN are zeros. Am I missing something here?

Best 
Stefan

**Comment by zarquon42b** [comment]
Forget it, I forgot to apply the IJK2RAS transform.
Best
Stefan
