### ISSUE TITLE
Removing ImageMath dependency

### ISSUE THREAD

**Issue by stnava** [stnava/ANTsR#53]
@jeffduda  @bkandel 

ANTsR will be "broken" for a while ... Being tired of this ongoing issue, I did the aggressive thing and removed imageMath and src/ImageMath.cpp and also updated the antstag s.t. ImageMath is not compiled in core.  here are the current issues:

```
* checking R code for possible problems ... NOTE
aslCensoring : aslOutlierRejection: no visible global function
  definition for ‘imageMath’
basicInPaint: no visible global function definition for ‘imageMath’
compcor: no visible global function definition for ‘imageMath’
getCentroids: no visible global function definition for ‘imageMath’
getTemplateCoordinates: no visible global function definition for
  ‘imageMath’
projectImageAlongAxis: no visible global function definition for
  ‘imageMath’
sliceTimingCorrection: no visible global function definition for
  ‘imageMath’
* checking Rd files ... OK
```

relating to:

```
ANTsR/R/aslCensoring.R:    imageMath(4, diffs, "TimeSeriesSimpleSubtraction", asl)
ANTsR/R/basicInPaint.R:  imageMath(img@dimension, temp, "MD", temp, 1)
ANTsR/R/basicInPaint.R:  # imageMath(img@dimension,paintMaskUse,'GD',paintMask,1)
ANTsR/R/basicInPaint.R:  imageMath(inpainted@dimension, inpainted, "FastMarchingExtension", speedimage,
ANTsR/R/compcor.R:    imageMath(4, myoutfn, "CompCorrAuto", fmri, mask, ncompcor)
ANTsR/R/getCentroids.R:  imageMath(imagedim, pointfile, "LabelStats", img, img, clustparam)
ANTsR/R/getTemplateCoordinates.R:  imageMath(milab@dimension, pointfile, "LabelStats",
ANTsR/R/pairwiseImageDistanceMatrix.R:        # broken !!  metric <- capture.output(imageMath(dim, 'j', metrictype, i1,
ANTsR/R/projectImageAlongAxis.R:  imageMath(imageND@dimension, downimg, "Project", imageND, axis, projtype)
ANTsR/R/sliceTimingCorrection.R:    imageMath(4, corrected, "SliceTimingCorrection", fmri, sliceTime, interpolation,
ANTsR/R/sliceTimingCorrection.R:    imageMath(4, corrected, "SliceTimingCorrection", fmri, sliceTime, interpolation,
ANTsR/R/sliceTimingCorrection.R:    imageMath(4, corrected, "SliceTimingCorrection", fmri, sliceTime)
```

here is a commit that deals with some of these:

https://github.com/stnava/ANTsR/commit/3713fd89d959ebfe6e22238bea646e75c0a153d5

however it would be good to get the rest as well ... 

@jeffduda  a few pieces of functionality in iMath

* Project  operator from ImageMath

* FastMarchingExtension

@bkandel    add  x, y, z, t  to labelStats ... the output is always 4D centroids ... e.g. in 2D it will contain  x_i, y_i, 0, 0  ( or maybe NA, NA ) ....

the other issues should be self explanatory.

**Comment by bkandel** [comment]
sounds good.  i already fixed the aslCensoring dependency, just waiting on
test suite to run before committing.

for the labelStats xyz coords, should i just use the raw output from
labelgeometryimagefilter, or is there some other space that the coordinates
should be drawn from?

2015-06-09 11:47 GMT-04:00 stnava <notifications@github.com>:

**Comment by stnava** [comment]
i forgot about labelGeometryMeasures, in part because it was broken.   so i will fix the calls to labelStats by using this instead.  so never mind about labelStats ....

**Comment by stnava** [comment]
done.

**Comment by stnava** [comment]
Remaining issues

```
MacBook-Pro:ANTsR stnava$ grep imageMath R/*
R/aslCensoring.R:    imageMath(4, diffs, "TimeSeriesSimpleSubtraction", asl)
R/sliceTimingCorrection.R:    imageMath(4, corrected, "SliceTimingCorrection", fmri, sliceTime, interpolation,
R/sliceTimingCorrection.R:    imageMath(4, corrected, "SliceTimingCorrection", fmri, sliceTime, interpolation,
R/sliceTimingCorrection.R:    imageMath(4, corrected, "SliceTimingCorrection", fmri, sliceTime)
```

**Comment by jeffduda** [comment]
We should probably just get rid of sliceTimingCorrection.R for now. It
makes a number of assumption which aren't true for data that is currently
being collected.

**Comment by stnava** [comment]
i am ok with that and will implement now.

any thoughts on the other 2:  (1) projection (2) fast marching extension  ?


brian

**Comment by jeffduda** [comment]
I can work on those today.

**Comment by jeffduda** [comment]
rather than make "project" part of iMath, i wrote apply.antsImage. This has
the advantage of being much more R-like and allowing an arbitrary function
to be used for the projection. It's just a wrapper for apply that handles
the header info.

**Comment by stnava** [comment]
that makes sense, of course.  probably very useful if we can figure out
what to do with it.

one issue is how to take care of the header info - guess you can wrap that
into apply.




brian

**Comment by stnava** [comment]
looks like `FastMarchingExtension` may be the only thing left ... that may
also be better off in a separate location than iMath ...


brian

**Comment by jeffduda** [comment]
Was thinking the same. Will make it, it's own .cpp

**Comment by stnava** [comment]
added some documentation to `FastMarchingExtension` and updated `basicInPaint` ... 

not sure the documentation has the right usage of the mask ... you might want clean that up / make sure it works with an example .... if you get a chance to do so, let me know.

**Comment by jeffduda** [comment]
Looks like apply isn't a generic so we can't make it work like we do with
plot, but as it is, apply.antsImage should handle all the header info and
work the same as a call to apply with an array

**Comment by stnava** [comment]
this is pretty close to done ... will close the issue once we get both codeship and travis passing ...

**Comment by stnava** [comment]
fixed an example bug.  this appears to be ready to close now.
