### ISSUE TITLE
abpBrainExtraction creating non-head voxel mask

### ISSUE THREAD

**Issue by BrysonBR** [stnava/ANTsR#55]
First, I want to say thanks for so quickly resolving my last abpBrainExtraction issue, it worked. But, I used a crappy "tem" and "temmask" so I got a crappy brain mask. In an effort to fix this I am trying to use the MNI standard brain as the template and it's very good brain mask as the template mask. I used the code below:
>ImageMath 3 close_MP1.nii.gz ClosestSimplifiedHeaderMatrix MP1.nii.gz
>ImageMath 3 close_MNI.nii.gz ClosestSimplifiedHeaderMatrix MNInew.nii.gz
>ImageMath 3 close_MNImask.nii.gz ClosestSimplifiedHeaderMatrix brainMask.nii
>
>struct<-antsImageRead("/Users/Bryson/Data/ANTsR_test/close_MP1.nii.gz")
>struct<-abpN4(struct)
>tem<-antsImageRead("/Users/Bryson/Data/ANTsR_test/close_MNI.nii.gz")
>tem<-abpN4(tem)
>temmask<-antsImageRead("/Users/Bryson/Data/ANTsR_test/close_MNImask.nii.gz")
>
>bm<-abpBrainExtraction(img=struct,tem=tem,temmask=temmask)
>
>antsImageWrite(bm$bmask, "MP1bmask.nii.gz")
>antsImageWrite(bm$brain, "MP1masked.nii.gz")

But the output I got looked more like a head-excluding mask than a brain-including mask.

I've attached the input and output files here:
https://drive.google.com/open?id=0B9oWACI5TJOEfm1KdzAxSG5IdlNZR3QyOEtGa3l2ZEVETHBUQXZyNDJGUGk5YXRNT2N4blk&authuser=0

Thanks again for your help!

**Comment by stnava** [comment]
looks like your brain mask has max values near 0.5

you should use a binary mask

also - see the ants cortical thickness paper for our philosophy on this (
custom templates )


brian

**Comment by BrysonBR** [comment]
You are correct, once I binarized the mask it ran well. I am getting an error, but it is not crashing and the output looks good. The error is:
> bad det -1 v 1 u -1
> bad det -1 v 1 u -1 new 1

I'm not sure if I should be worried about it or not.
I'll read that paper you suggested to get a better understanding of the templates, thanks again.

**Comment by stnava** [comment]
thats nothing to worry about.


brian

**Comment by stnava** [comment]
also, you may not have to use the "closest" trick with this setup i.e. when
mapping to MNI


brian

**Comment by BrysonBR** [comment]
Thanks, I appreciate all of your help and guidance.
