### ISSUE TITLE
BUG:  apply.antsImage combined with plot

### ISSUE THREAD

**Issue by stnava** [stnava/ANTsR#56]
sort of a dual bug ... apply.antsImage gives you some junky header info and plot fails when it gets this - presumably actually cropImage fails .... 

but quite nasty because of the segfault

``` 
tslice=apply.antsImage( img, c(1,3,4), mean )
plot(tslice)
ITK ExceptionObject caught !

itk::ExceptionObject (0x7faac52003c8)
Location: "unknown" 
File: /Users/stnava/code/RLibs/ITKR/libs/include/ITK-4.8/itkImageBase.hxx
Line: 193
Description: itk::ERROR: Image(0x7faac3dbbe70): Bad direction, determinant is 0. Direction is -0 -1 0
0 0 0
0 0 1



libc++abi.dylib: terminating with uncaught exception of type Rcpp::exception: ITK exception caught
Abort trap: 6
MacBook-Pro:wetransfer-2bfbfc stnava$ plot(tslice)
-bash: syntax error near unexpected token `tslice'
```

**Comment by bkandel** [comment]
looks like incomplete error handling in cropImage to me...

2015-06-18 9:08 GMT-04:00 stnava <notifications@github.com>:

**Comment by jeffduda** [comment]
can you print out the header info on img and tslice, curious as to what is
going on with that.

**Comment by stnava** [comment]
it's just any case that has a matrix like this ( i.e. off diagonal )

[ 0 1 0
  1 0 0
  0 0 1 ]

if you select the lower right sub matrix, it becomes degenerate.

so, if apply.antsImage puts that into the image, then that image

will cause anything downstream to fail.  which is why there is

the "collapse to identity" option.


brian

**Comment by jeffduda** [comment]
ok, should be fixed in apply.antsImage now and antsSetDirection was fixed
to check for a bad matrix and report an error instead of seg faulting
