### ISSUE TITLE
plot antsimage: incorrect overlay in coronal

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#57]
This used to work before (when plot was creating a single raw of slices) but not anymore. I load a 3D image, and plot it with an overlay. Axial and Sagittal axis plots work ok, but Coronal doesn't work with overlay. It is not a discrepancy between images, does the same when you try to overlay the image onto itself:
plot(t1, t1, axis=2)

Maybe Ben has forgot to fix something...

**Comment by stnava** [comment]
addressed with https://github.com/stnava/ANTsR/commit/c62abab6544492b8134bf9a4209b5c345791dff8

see https://github.com/stnava/ANTsR/wiki/Image-plotting-example-with-multiple-overlays

**Comment by dorianps** [comment]
Another part that may need attention is overlay transparency. I had to make a small hack to make it work properly in local. But requires more attention to get it fixed properly.

**Comment by stnava** [comment]
ok - separate issue.


brian
