### ISSUE TITLE
Some objects are included as functions but cpp not included

### ISSUE THREAD

**Issue by muschellij2** [stnava/ANTsR#6]
For example:

WarpImageMultiTransform()
Error in .Call("WarpImageMultiTransform", as.character(c(...))) : 
  "WarpImageMultiTransform" not resolved from current namespace (ANTsR)

I think this example is important because right now you can transform into a fixed space, perform operations, but you cannot go back into the moving space afterward.

**Comment by stnava** [comment]
should be (mostly) resolved with commit f0015689c179568bd58a43cf26d9385183e07478
