### ISSUE TITLE
Random Field Theory Function

### ISSUE THREAD

**Issue by Tokazama** [stnava/ANTsR#62]
Sometime around August I posted a question about performing VBM analyses on the sourceforge discussion forum for ANTs. At the time I was trying to transition our lab from using the SPM toolbox in Matlab to ANTsR. Dr. Avants responded with suggestions to make the SCCAN technique work for us.. He also mentioned that development of SPM like functions might be welcome. Without going into too much detail, after reading more on the topic I realized that it would be beneficial to be able to implement some of the statistical techniques utilized in SPM into R.

Since then I've spent a significant amount of time developing several functions that could implement random field theory into R. I've relied heavily upon Worsley et al.'s 'A unified statistical approach for determining significant signals in images of cerebral activation to implement some math that has resulted in comparable results to SPM.  It's still not entirely complete but I have designed the functions to work within ANTsR. I was wondering if this might be something you want to include in ANTsR.

**Comment by stnava** [comment]
that would be a fantastic contribution.  it would be truly ideal if you can implement roxygen2 documentation for each contributed function that includes examples, authors (yourself) and references to worsley.  ideally, the examples should be fast and self-contained and should illustrate usage clearly to the reader.   see https://github.com/stnava/ANTsR/blob/master/R/eanatDef.R#L1-L35 as a guide or, better, examples written by hadley wickham.  if you could do this via pull request, even better.  let me know if you need further feedback & glad to hear you have progress and agree with the principle of moving away from matlab and toward R for stats in medical imaging.

**Comment by bkandel** [comment]
This would be fantastic!  There are a bunch of optimized ITK functions
available for getting connected regions which may also be of use -- let us
know if you need some help using them.

2015-12-01 13:23 GMT-05:00 stnava <notifications@github.com>:

**Comment by bkandel** [comment]
If you could package your changes as a fork (
https://help.github.com/articles/fork-a-repo/), you can submit a pull
request easily (https://help.github.com/articles/using-pull-requests/).

2015-12-01 15:28 GMT-05:00 Ben Kandel <ben.kandel@sbcglobal.net>:

**Comment by Tokazama** [comment]
I'll get started on putting together the documentation and examples. I've only briefly looked at the possibility of using ITK. This is because I don't really understand C++ code and because the only function  I've needed that isn't already in the ANTsR package is calculating resels. The calculation of which requires a very specific evaluation of each voxel in relation to its neighbor voxels. I've developed an R function that can evaluate it, but if ITK can do it better that'd be great.

**Comment by stnava** [comment]
one other thought - keep your function examples clear and concise.  then
put together a vignette (that should still be fast) but that shows a more
complete statistical mapping example linking together your different
functions.


brian

**Comment by Tokazama** [comment]
One issue I haven't yet resolved is how to acquire an estimate of smoothing in cortical thickness.

**Comment by Tokazama** [comment]
I've most likely finished the bulk of what exclusively relates to random field theory and done some rudimentary comparisons against SPM [here](https://github.com/Tokazama/rft/blob/master/tests/checks.Rmd) to ensure the functions perform accurately. Most of the function specific documentation is complete and I'm currently finishing up fixing some of the naming to better fit with ANTsR. I also need to establish a complimentary method of fitting models within R before I put together a good vignette. My understanding is that the standard in most software has been drawn from Friston et al., (2002) Classical and Bayesian Inference in Neuroimaging: Theory. Unless you have any suggestions my plan is to attempt to develop something like this.

Also, I'm interested in Ben's suggestion of using ITK to speed things up. I've been studying up on C++ and quickly put together a script using RcppArmadillo for calculating resels. However, I hesitate to add more dependencies if ITK has an equal or better method of doing it. Is there any functionality in ITK I could look into that might be better. For reference, the equivalent R based function is [here](https://github.com/Tokazama/rft/blob/master/R/resels.R) and basically uses subsets of arrays to determine relationships between voxels.

**Comment by stnava** [comment]
i did not read the code very closely but the main comment is this:  it would be ideal if it was implemented in an N-dimensional manner.   and preferably without `if` statements.  the operations look very straightforward so it should not be too difficult.  i would recommend keeping your reference implementation until you can figure out a faster/validated N-D version.    using ITK is likely to be the easiest way to implement in ND.   see https://github.com/stnava/ANTsR/blob/master/src/smoothImage.cpp for an example of how to pass data back and forth.   image iterators in ITK and/or filters (Add, subtract, multiply) are fast ways to do this and, if  you use filters to add / multiply / subtract, then you get the added bonus of multi-threading.  @jeffduda may be a good person to consult for implementation details.

**Comment by jeffduda** [comment]
Happy to help with Rcpp/ITK integration. If no existing filters are
suitable then it's probably worth writing one rather than using iterators,
due to the multi-threading bonus.

**Comment by stnava** [comment]
@Tokazama minor documentation issue visible here https://s3.amazonaws.com/archive.travis-ci.org/jobs/119613813/log.txt

```

Documented arguments not in \usage in documentation object 'statFieldThresh':
  â€˜maskâ€™
```

looks to be related to functionality that may not be implemented ... mask is referenced in `	\item{pRFT: }`
