### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by muschellij2** [stnava/ANTsR#63]
I think the dev version should have a different version on github (0.3.1 is the release and the current version).  Without changing this, it's hard to know which true version of the package is being used.

**Comment by stnava** [comment]
agree and would welcome a patch


brian

**Comment by stnava** [comment]
address this with: https://github.com/stnava/ANTsR/commit/aaadceeaf4551b57010586d8353657d2bbd79489

added some clarification to `README.md`

all the same, recommend using the git hashtag to track code.  the major.minor.patch approach is an approximation that @stnava is not very skilled at maintaining.

**Comment by muschellij2** [comment]
So when do you guys update major/minor versions in the DESCRIPTION file?
