### ISSUE TITLE
BOLD realignment without motion correction

### ISSUE THREAD

**Issue by BrysonBR** [stnava/ANTsR#65]
In ANTsR, is there a function to do realignment of the 4d BOLD images without regressing out the motion parameters? Or, should I just use antsRegistration.R to register each time point to a reference time point?

**Comment by ntustison** [comment]
``antsMotionCorr.R``

**Comment by BrysonBR** [comment]
Thank you.

**Comment by stnava** [comment]
`antsApplyTransforms` will apply a 3D transform to a 4D image.

the mocoimg that is output from the motion correction routine is
transformed only

by the internal parameters.

you can also pass whatever reference you like as the fixed image.  here is
an example, could be cleaner, sorry.

```

mocoImg <- new("antsImage", "float", 4)

aimg <- new("antsImage", "float", 3)

mocoParams <- new("antsMatrix", "double")

simimg <- antsImageRead(getANTsRData('pcasl'), 4)

mni = antsImageRead( getANTsRData("mni" ) ) %>% resampleImage( c(60,60,60),
useVoxels=1 )

kk = antsMotionCorr( list( d = 3 ,

  o = list( mocoParams , mocoImg , aimg ) ,

  m = list( name = "MI" , mni , simimg , 1 , 32 , "Regular", 0.1 ) ,

  t = "Rigid[0.01]" , i = 25 ,

  u = 1 , e = 1 , s = 0 , f = 1 , n = 25 ) )

```


brian

**Comment by BrysonBR** [comment]
Thanks again.
