### ISSUE TITLE
AMI installation has problems

### ISSUE THREAD

**Issue by moleps** [stnava/ANTsR#67]
I´ve tried both the drat and devtools approaches to ANTsR installation after installing cmaker. However, upon installing ITKR I get the following error msg. It works allright on Mac OS, but I cannot finish the installation on a EC2 ubuntu 14.04 instance. Any ideas?

HEAD is now at c98c5dd... Merge topic 'BSplineTimeVaryingWithPoints'
./configure: line 25: cmake: command not found
ERROR: configuration failed for package ‘ITKR’

**Comment by stnava** [comment]
maybe install cmake via

http://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu-14-04

then proceed with ITKR + ANTsR

check travis builds to see how we install on the fly for testing.


brian

**Comment by moleps** [comment]
I started a new instance and created a new AMI with a fresh rstudio server installation. I installed cmake 2.8 from shell and the ITKR installation went allright. Next, I tried installing ANTsR but I first had to remove 00LOCK-stnava-ANTsR-ca114f8 directory in order for it to compile at all. However, the ANTsR installation throws an error at the end (?) of the compilation:

g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I`/usr/lib/R/bin/Rscript -e 'ITKR:::itkIncludes()'` -I/tmp/RtmppnD0fc/devtools561220217e6/stnava-ANTsR-ca114f8/src -I/tmp/RtmppnD0fc/devtools561220217e6/stnava-ANTsR-ca114f8/src/ants//Examples/include/ -I/tmp/RtmppnD0fc/devtools561220217e6/stnava-ANTsR-ca114f8/src/ants//Utilities -I/tmp/RtmppnD0fc/devtools561220217e6/stnava-ANTsR-ca114f8/src/ants//Examples/ -I/tmp/RtmppnD0fc/devtools561220217e6/stnava-ANTsR-ca114f8/src/ants//Tensor/ -DVCL_CAN_STATIC_CONST_INIT_FLOAT=0  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2/ITKR/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c antsRegistration.cpp -o antsRegistration.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I`/usr/lib/R/bin/Rscript -e 'ITKR:::itkIncludes()'` -I/tmp/RtmppnD0fc/devtools561220217e6/stnava-ANTsR-ca114f8/src -I/tmp/RtmppnD0fc/devtools561220217e6/stnava-ANTsR-ca114f8/src/ants//Examples/include/ -I/tmp/RtmppnD0fc/devtools561220217e6/stnava-ANTsR-ca114f8/src/ants//Utilities -I/tmp/RtmppnD0fc/devtools561220217e6/stnava-ANTsR-ca114f8/src/ants//Examples/ -I/tmp/RtmppnD0fc/devtools561220217e6/stnava-ANTsR-ca114f8/src/ants//Tensor/ -DVCL_CAN_STATIC_CONST_INIT_FLOAT=0  -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2/ITKR/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c antsTransform.cpp -o antsTransform.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make: *** [antsTransform.o] Error 4
ERROR: compilation failed for package ‘ANTsR’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2/ANTsR’
Error: Command failed (1)
In addition: Warning message:
GitHub repo contains submodules, may not function as expected!

**Comment by muschellij2** [comment]
I would try to git clone ITKR and ANTsR and run R CMD install from command line

**Comment by stnava** [comment]
That error is very likely to be caused by a lack of RAM. ants is very
template heavy in this leads to a large memory footprint during
compilation. This is one reason that we recommend using clang.

**Comment by moleps** [comment]
So I did the CLI installation without any success. However, installing from CLI after increasing the instance memory it worked out fine in the end. Appreciate the quick feedback - thx and happy new year.
