### ISSUE TITLE
Occasional failed brain extractions

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#82]
I am using abpN4 -> abpBrainExtraction to get brain masks. One of the problems I notice is that occasionally the mask includes some non-brain tissue. The problem occurs in about 10% of the cases, and in some is more visible than the others. Here is a sample of the problem. In green is the boundary of the brain mask obtained from the above commands. The subject has three MRI modalities: T1, T2, FLAIR, but only T1 is used for brain extraction. I tried to figure out what can make a brain mask get so wrong, but can't think of something.

![image](https://cloud.githubusercontent.com/assets/9083517/13165213/1f62c40e-d689-11e5-8231-cb86300d8c37.png)

Is there anything I can do to fix these cases? It doesn't look like a registration problem with the reference template.

**Comment by ntustison** [comment]
What template are you using?  It appears the image boundaries are pretty tight to this particular subject and if that is characteristics of the cohort then you might want to consider making your own mask.

**Comment by dorianps** [comment]
I use the same template build for the LINDA paper, build from 208 healthy+diseased cases. It's available here:
https://github.com/dorianps/LINDA/tree/master/pennTemplate

I haven't checked everyone but for this case you are right that boundaries are tight:

![image](https://cloud.githubusercontent.com/assets/9083517/13165699/153c637c-d68e-11e5-9ade-c054834af680.png)

When you say build my own mask, what do you mean exactly, I am not sure I understand.

Thank you

**Comment by dorianps** [comment]
By the way, if I remember correctly these data are all from co-registration to an MNI template done in SPM. I think that procedure is cutting the excess empty boundaries. Yet, I don't understand why some are ok and others fail, despite being on the same template space.

If necessary I can upload the pdf with all 40 cases for an overview (115Mb).

**Comment by ntustison** [comment]
The template space might be the same but each subject is different.  I wouldn't expect each subject to get processed the same.

By building your own mask, I meant build your own template and mask.  The choice of template and mask is probably the biggest factor in results quality.

**Comment by dorianps** [comment]
Thank you Nick.

Since we are here, I's like to ask about a slightly different issue on brain extraction. I usually extract brains of patients with stroke. The problem is that they don't have the whole brain, so the mask eats up the excess CSF to get close to where the brain is. This creates a problem when I use the mask to estimate where the brain should have been (i.e. the lesion).

Here is an example (green=brain extraction, red=manually traced lesion):
![image](https://cloud.githubusercontent.com/assets/9083517/13177351/99b937da-d6e6-11e5-958b-5a65325102b9.png)

Is there any solution you might think for this? Could masking the lesion during template registration fix brain extraction?

I know this is not a common problem but maybe someone has an idea how to resolve this issue for good.

**Comment by ntustison** [comment]
I don't know about resolving the problem for good but, if you have a lesion mask, you could "or" the lesion mask and brain extraction mask.  You might then need to follow up with some morphological closing operations.

**Comment by dorianps** [comment]
I guess that works for pre-traced lesion. The problem arises when predicting the lesion in new patients, in which case the creation of the lesion mask itself is constrained by the brain mask itself.

**Comment by stnava** [comment]
i would guess that an affine registration or low-dimensional registration
might give you some extra rigidity that could help as a prior or 2nd guess
of where the boundary should be.

would be interesting to build a bayesian model for this problem ...
although antsJointFusion may be similar to that.


brian

**Comment by cookpa** [comment]
How well is the standard registration doing? The call to antsBrainExtraction returns the registration transforms - you can use these to warp the template brain mask to the subject space. It might be the segmentation step in aBE that is eroding the CSF away.

**Comment by ntustison** [comment]
I was going to agree with what Phil said---just use joint label fusion with majority voting and B-spline SyN to give a stiffer elastic transform.

**Comment by dorianps** [comment]
Alright, thanks for your inputs. Will try these. Closing issue.
