### ISSUE TITLE
SyN taking 5-10 times longer than before

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#87]
I used to get 5 minutes antsRegistration('SyN') before, and now it needs ~30-60 minutes. The voxel resolution of my new images is a bit higher than before (0.6x1x1 vs 1x1x1 mm, always T1 weighted) but I see also some changes are made to the function.

What might be the problem here? Did one of the recent changes push the computation times so much or is it explained only by changes in code?

**Comment by stnava** [comment]
i think the question is: how long does the registration take on the *old* images ... i.e. if you don't double the resolution. registering images at 0.6x1x1 will take much longer than at 1^3 ... you can downsample to 1^3 before registration, if you want to keep computation time 'the same'.  another factor is the number of voxels at a given resolution.
