### ISSUE TITLE
useAbsoluteScale in plot.antsImage

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#91]
I thought useAbsoluteScale should plot the full range of the overlay, but is not coded to do so, and it does not do it.

If this parameter is for something else, I suggest we get a new parameter to easily plot the full range. This is often useful when plotting labels.

If this is the parameter that should do it I can try to fix the code to make it do that.

**Comment by stnava** [comment]
see ?plot.antsImage  window.* ... the scale is set by the parameter window.overlay ... if you set window.overlay = c(  0, 100 ) then any image overlay will map into that range.

**Comment by dorianps** [comment]
Yes, but rather than having to find the min/max values and set windows.overlay, wouldn't it be easier to tell plot() to avoid truncating intensities. Whether in interactive mode or in scripting, setting windows.overlay adds commands each time plot is called.
